import { tabloBul } from "./constants.js";
// hata-kodlari.js — TAMİR MERKEZİ ① KATMAN: HATA KODU / BELİRTİ GİRİŞİ (YK Kararı #35, 3 Ağu 2026)
//
// NE İŞE YARAR: kullanıcı `/tamir/<cihaz>/` sayfasına elindeki **hata kodu** ya da **belirti**
// ile girer; sayfa ona sırasıyla "bu ne demek" ve "ne yapmalı"yı gösterir, sonra ya
// **kendi rehberimize** ya da **servis çağırma yoluna** çıkarır.
//
// ⛔ NEDEN BU DOSYA VAR (YK #35 gerekçesi): en çok gösterim alan üç sayfamızın hiçbiri DIY
// içeriği değil — `bosch-camasir-makinesi-hata-kodlari` (624), `ocak-atesleme-yapmiyor` (601),
// `derin-dondurucu-kac-derece-olmali` (499). Talep hata kodu / arıza teşhisi / ayar tarafında;
// Tamir Merkezi "kendin-yap kütüphanesi" değil, **üç katmanlı teşhis merkezi** olarak kuruldu.
//
// ⛔ İÇERİK ÜRETİLMEDİ (rol sınırı — metin PAZ'ın işi):
//   · Buradaki her kayıt, ZATEN YAYINDA olan kendi yazımıza bağlanır. Yeni yazı/rehber YOK.
//   · `anlam` alanı yazının kendi frontmatter'ındaki özetten damıtılmış TEK satırlık
//     gezinme etiketidir — yeni iddia, yeni bilgi, yeni tavsiye içermez.
//   · Yazıların `description` alanı sayfaya BASILMAZ: o metinler fiyat/maliyet ifadesi
//     içeriyor, ① katman ise fiyat geçmeyen bir katman (aşağıya bak).
//
// ⛔ FİYAT YASAĞI (YK #35, bağlayıcı — MALİYET KATMANI KİLİTLİ):
//   `/tamir/` altındaki hiçbir sayfada TL/₺/fiyat/ücret/maliyet ifadesi geçmez ve "yakında"
//   da yazılmaz. Bu dosyadaki metinler de o kurala tabidir; `scripts/build-blog.mjs` içindeki
//   `fiyatDenetimi()` üretilen HTML'i tarar ve ihlalde build'i DURDURUR (elle gözle kontrol yok).
//   Gerekçe (Rıza şerhi): tarife verisi 19 Haz'dan donmuş, bilinen bir kalemde piyasadan
//   %20-40 sapıyor; yayınlanırsa tahmin değil, kurumsal fiyat vaadi olur.
//
// ⛔ KAPSAM (YK #31): `rehber: true` yalnız ücretsiz/bakım seviyesi işlere konur. Parça
//   değişimi/söküm gerektiren bir kayıt buraya rehber olarak GİRMEZ — o kayıt servis yoluna çıkar.
//
// ALAN SÖZLÜĞÜ
//   giris  → kullanıcının elindeki şey: hata kodu ("E22", "F.28") ya da belirti ("Su almıyor")
//   tip    → "kod" | "belirti" | "ayar"   (sayfada bu üç başlık altında gruplanır)
//   anlam  → tek satır "bu ne demek" (fiyat/ücret/maliyet kelimesi YASAK)
//   yazi   → kendi blog yazımızın slug'ı (URL DEĞİŞMEZ: /blog/<slug>/). Boşsa servis yoluna çıkar.
//   rehber → true ise bu kayıt aynı zamanda KENDİ bakım rehberimizdir (② kendin-çöz katmanı);
//            kartın zorluk/süre/adım meta'sı `src/onarim-rehberleri.js`'ten okunur, burada tekrarlanmaz.

export const HATA_KODU_KATMANI = {
  "Çamaşır Makinesi": [
    { giris: "Bosch · Siemens · Neff — E ve F kodları", tip: "kod",
      // 22 Ağu (TARAMA-1): F21 ve F63 çıkarıldı — ikisi de 5 BSH bölge sitesinde ve
      // 5 kılavuzda yok. BSH'nin tahrik kodu E80. (Yazının gövdesi ayrıca ele alınacak.)
      anlam: "E16, E17, E18, E23, E80… hangi kod ne demek, hangisi evde çözülür hangisi servis ister.",
      yazi: "bosch-camasir-makinesi-hata-kodlari" },
    // 22 Ağu 2026 (TARAMA-1): kod ailesi düzeltildi. Üreticinin çamaşır makinesi listesi
    // TEK HANELİ (E5·E8·E12·E17·E18·E27·E29·E84·Err·SC); E01–E11 bandı ve H1/H4/H5 yok.
    // Listede ayrı bir KAPI KİLİDİ ve ayrı bir ISITMA kodu da yok — eski giriş ikisini
    // de sayıyordu. Grundig kendi kod tablosunu yayımlamadığı için başlıktan çıkarıldı.
    { giris: "Arçelik · Beko — E5, E8, E12, E17, E18", tip: "kod",
      anlam: "Üreticinin yayımladığı on kodun karşılığı; hangisi evde çözülür, hangisi servis ister.",
      yazi: "arcelik-camasir-makinesi-hata-kodlari" },
    { giris: "LG — IE, OE, UE, dE", tip: "kod",
      anlam: "LG panelindeki iki harfli kodların anlamı ve hangisini kendin çözebilirsin.",
      yazi: "lg-camasir-makinesi-hata-kodlari" },
    { giris: "Samsung — 4E/4C, 5E/5C, UE", tip: "kod",
      anlam: "Samsung'un su alma, tahliye ve denge kodlarının karşılığı.",
      yazi: "samsung-camasir-makinesi-hata-kodlari" },
    { giris: "Marka fark etmeksizin en sık kodlar", tip: "kod",
      anlam: "Markası listede yoksa buradan bak: en sık kodların ortak anlamı.",
      yazi: "camasir-makinesi-hata-kodlari" },
    { giris: "Kod yok, ışıklar yanıp sönüyor", tip: "kod",
      anlam: "Ekranı olmayan modellerde yanıp sönen ışık dizilimi de bir hata bildirimidir.",
      yazi: "camasir-makinesi-isik-yanip-sonuyor" },
    { giris: "Su atmıyor / çamaşırlar ıslak çıkıyor", tip: "belirti",
      anlam: "Çoğu durumda tahliye filtresi tıkalıdır; filtreyi kendin temizleyebilirsin.",
      yazi: "camasir-makinesi-tahliye-filtresi-temizleme", rehber: true },
    { giris: "Su almıyor", tip: "belirti",
      anlam: "Önce musluk, giriş filtresi ve hortum kontrol edilir.",
      yazi: "camasir-makinesi-su-almiyor" },
    { giris: "Sıkarken ses ve titreşim", tip: "belirti",
      anlam: "Nakliye cıvatası, dengesizlik, yabancı cisim ve rulman ayrımı nasıl yapılır.",
      yazi: "camasir-makinesi-ses-titresim" },
    { giris: "Küf / rutubet kokusu", tip: "belirti",
      anlam: "Kapı contası, deterjan çekmecesi, filtre ve kireç kaynaklı kokunun nedenleri.",
      yazi: "camasir-makinesi-kokuyor", rehber: true },
    { giris: "Hangi çamaşır kaç derecede yıkanır", tip: "ayar",
      anlam: "30-40-60-90 derece seçimi ve makinede koku yapmaması için tek kural.",
      yazi: "camasir-kac-derecede-yikanir" },

  // ——— Boşluk dalgası (20 Ağu 2026, YK — 85-konu taraması) ———
    { giris: "Beko — E5, E8, E12, E27, E29, Err, SC", tip: "kod",
      anlam: "Beko'nun yayımladığı on kodun karşılığı; evde bakılacaklar ve servis sınırı.",
      yazi: "beko-camasir-makinesi-hata-kodlari" },
    // 22 Ağu (TARAMA-1): Beko listesinde E10 YOK — su alma kodu E8. Yazının adresi
    // korundu (arama gerçek), girişi doğrusuna çevrildi.
    { giris: "Beko — su alamıyor (aranan kod E10, doğrusu E8)", tip: "kod",
      anlam: "Musluk, hortum ve giriş süzgeci kontrolüyle çoğu zaman evde çözülür.",
      yazi: "beko-camasir-makinesi-e10-hatasi" },
    { giris: "Siemens — E18, F21, E23", tip: "kod",
      anlam: "Her kodun anlamı, hangisinin evde çözüldüğü ve hangi noktada servis gerektiği.",
      yazi: "siemens-camasir-makinesi-hata-kodlari" },
    // 22 Ağu (TARAMA-1): F21 çıkarıldı — BSH'nin hiçbir bölge sitesinde ve kılavuzunda
    // yok. Tahrik/motor kodu E80. Bosch TR'nin yayımladığı liste: E16-E20, E23, E25-E28.
    { giris: "Profilo — E17, E18, E23 (F21 yok)", tip: "kod",
      anlam: "BSH ailesindeki bu kodların anlamı; evde çözülebilenler ve servis gerektirenler.",
      yazi: "profilo-camasir-makinesi-hata-kodlari" },
    { giris: "Vestel — E01, E02, E03", tip: "kod",
      anlam: "Kapı, su alma ve tahliye kodlarının anlamı ve evde yapılacak kontroller.",
      yazi: "vestel-camasir-makinesi-hata-kodlari" },
    { giris: "Çalışmıyor / start almıyor", tip: "belirti",
      anlam: "Çoğu zaman priz, sigorta, kapak kilidi ya da çocuk kilididir; servisten önce bakılacak 5 nokta.",
      yazi: "camasir-makinesi-calismiyor" },
    { giris: "Sigorta attırıyor", tip: "belirti",
      anlam: "Elektrik güvenliği uyarısıdır: fişi çek, tekrar deneme; teşhis servise aittir.",
      yazi: "camasir-makinesi-sigorta-attiriyor" },
    { giris: "Su kaçırıyor / alttan su sızdırıyor", tip: "belirti",
      anlam: "Kaynak çoğu zaman deterjan çekmecesi, hortum bağlantıları ya da filtre kapağıdır; güvenli kontrol sırası.",
      yazi: "camasir-makinesi-su-kaciriyor" },
    { giris: "Çamaşırlarda leke bırakıyor", tip: "belirti",
      anlam: "Siyah-gri leke ve pas izinin kaynağı makinenin kendisidir: conta küfü, kirli tambur ya da içeride kalmış cisim.",
      yazi: "camasir-makinesi-camasirlarda-leke-birakiyor" },
    { giris: "Deterjanı almıyor / çekmecede su kalıyor", tip: "belirti",
      anlam: "Çoğu zaman su basıncı ya da tıkanmış çekmecedir; temizliği kendin yapabilirsin, giriş valfi servis işidir.",
      yazi: "camasir-makinesi-deterjan-almiyor" },
    { giris: "İçine cisim kaçtı (sütyen teli, madeni bozukluk)", tip: "belirti",
      anlam: "Cismin nereye gittiği, filtreden güvenle nasıl çıkarılacağı ve hangi durumda servisin şart olduğu.",
      yazi: "camasir-makinesine-cisim-kacti" },
    { giris: "Deterjan çekmecesi: hangi göz ne için", tip: "ayar",
      anlam: "I, II ve çiçek sembollerinin anlamı, sıvı deterjanın konacağı göz ve yumuşatıcının taşma sebebi.",
      yazi: "camasir-makinesi-deterjan-cekmecesi-hangi-goz" },
    { giris: "Ne kadar elektrik harcar", tip: "ayar",
      anlam: "Enerjinin çoğu suyu ısıtmaya gider: 30-40-60 derece farkı, eko program gerçeği ve tüketimi düşüren alışkanlıklar.",
      yazi: "camasir-makinesi-ne-kadar-elektrik-harcar" },
  // ——— 21 Ağu boşluk dalgası tur-2 (25 yeni yazı) ———
    { giris: "Bosch · Siemens — E18", tip: "kod",
      anlam: "Makine suyu atamıyor: tahliye pompası, filtre ve hortum sırasıyla eleniyor; çoğu evde çözülüyor.",
      yazi: "bosch-camasir-makinesi-e18-hatasi" },
    { giris: "Vestel — E03", tip: "kod",
      anlam: "Tahliye süresi aşıldı demek; pompa filtresi ve gider hortumu kontrolüyle başlıyorsun.",
      yazi: "vestel-camasir-makinesi-e03-hatasi" },
    { giris: "Su alıyor ama tambur dönmüyor", tip: "belirti",
      anlam: "Kayış, motor kömürü, kapı kilidi ve program ayrımı; hangisi evde bakılır hangisi servis işi.",
      yazi: "camasir-makinesi-tambur-donmuyor" },
    { giris: "Hızlı program ne zaman kullanılır", tip: "ayar",
      anlam: "Hızlı program hangi kirde işe yarar, hangisinde yıkamayı yarım bırakır.",
      yazi: "camasir-makinesi-hizli-program-ne-zaman" },
  // ——— 21 Ağu tur-3: tıklama odaklı kod + karar dalgası (12 yazı) ———
  // ⛔ `firin-tamiri-kac-para` ve `televizyon-tamiri-kac-para` BİLEREK BAĞLANMADI:
  //    başlıklarındaki "para" kelimesi kategori sayfasına sızıyor ve YK #35 şart 1'i
  //    ihlal ediyor (build 21 Ağu'da 3 sayfada yakaladı). Mevcut "…kaç para" yazıları da
  //    aynı sebeple bu ağaçta yok — istisna açılmadı. O yazılar /blog/ tarafında yaşıyor.
    // 22 Ağu (TARAMA-1): Grundig kendi kod tablosunu YAYIMLAMIYOR; kılavuzlarında kod
    // değil belirti tablosu var. Eski giriş doğrulanmamış altı kod sayıyordu.
    { giris: "Grundig — kod tablosu yok, belirti tablosu var", tip: "kod",
      anlam: "Grubun yayımladığı ortak liste, kılavuzdaki belirti-sebep tablosu ve evdeki kontroller.",
      yazi: "grundig-camasir-makinesi-hata-kodlari" },
    { giris: "Kireç ve tambur temizliği (planlı bakım)", tip: "ayar",
      anlam: "Boş bakım yıkaması ne sıklıkta, kapak lastiğinin katları ve suyun sertliğiyle ilişkisi.",
      yazi: "camasir-makinesi-kirec-ve-tambur-temizligi" },
  ],

  // ── KURUTMA MAKİNESİ (21 Ağu 2026: Tolga kararıyla AYRI CİHAZ oldu) ───────────────
  // Bu 5 kayıt "Çamaşır Makinesi" altında duruyordu; kurutma ayrı cihaz olunca kendi
  // /tamir/kurutma-makinesi/ sayfasına taşındı. Kayıtların METNİ ve bağlı YAZISI
  // değişmedi — yalnız hangi cihazın altında durdukları değişti.
  "Kurutma Makinesi": [
    { giris: "Kurutma makinesi — Arçelik ve Beko panel sembolleri", tip: "kod",
      anlam: "İki markanın kılavuzunda da kod değil sembol var; ekransız modellerde ışık dili.",
      yazi: "kurutma-makinesi-hata-kodlari" },
    { giris: "Kurutma makinesi ısıtmıyor / soğuk üflüyor", tip: "belirti",
      anlam: "Sorun çoğu zaman hava akışında başlar: filtre, kondenser, güvenlik termiği sırasıyla izlenir.",
      yazi: "kurutma-makinesi-isitmiyor" },
    { giris: "Kurutma makinesi su tankı dolu uyarısı", tip: "belirti",
      anlam: "Tank boşken de uyarı verebilir; tankın oturuşu, şamandıra ve kondenser tıkanıklığı kontrol edilir.",
      yazi: "kurutma-makinesi-su-tanki-dolu-uyarisi" },
    { giris: "Kurutma makinesi filtre ve kondenser temizliği", tip: "ayar",
      anlam: "Kurutma süresi uzadıysa ilk bakılacak yer: kapak filtresi her kurutmada, kondenser ayda bir temizlenir.",
      yazi: "kurutma-makinesi-filtre-ve-kondenser-temizligi" },
    { giris: "Kurutma makinesi ne kadar elektrik harcar", tip: "ayar",
      anlam: "Isı pompalı ve kondenserli modellerin farkı; tıkalı filtre tüketimi artırır.",
      yazi: "kurutma-makinesi-ne-kadar-elektrik-harcar" },

  // ——— Kayıt genişletmesi (21 Ağu 2026, YK #80 · hedef 200+) ———
    { giris: "Program bitti ama kapak açılmıyor", tip: "belirti",
      anlam: "Kilit program bitiminden 1-3 dakika sonra çözülür; kazanda su varsa makine kapağı bilerek açmaz.",
      yazi: "camasir-makinesi-kapagi-acilmiyor" },
    { giris: "Sıkma yapmıyor, çamaşırlar sırılsıklam çıkıyor", tip: "belirti",
      anlam: "Çoğu zaman makinenin kendini koruma davranışıdır: yük dengesi, seçili devir, kalan su ve makinenin terazisi sırayla bakılır.",
      yazi: "camasir-makinesi-santrifuj-yapmiyor" },
    { giris: "Tambur suyla dolu kaldı, program bitmiyor", tip: "belirti",
      anlam: "Makine suyu boşaltamazsa son adıma geçemez; ilk durak alt kapaktaki tahliye filtresidir.",
      yazi: "camasir-makinesi-su-atmiyor" },
    { giris: "Program kaç saat sürer (pamuklu 60, sentetik 40)", tip: "ayar",
      anlam: "Üretici kılavuzlarından derlenen gerçekçi süre bantları; ekrandaki ilk süre bir tahmindir, makine yükü tartınca güncellenir.",
      yazi: "camasir-makinesi-program-sureleri" },
    { giris: "Kurutma programı bitti, çamaşır hâlâ nemli", tip: "belirti",
      anlam: "Sebep çoğu zaman hava akışının kısıtlanmasıdır: tiftik filtresi, yoğuşma haznesi ve yoğuşturucu sırayla kontrol edilir.",
      yazi: "kurutma-makinesi-kurutmuyor" },
    { giris: "Suyu boşaltmadan durdu", tip: "belirti",
      anlam: "Tahliye tarafında tıkanıklık işareti: filtre, hortum ve yük dengesi kontrol edilir.",
      yazi: "camasir-makinesi-su-atmiyor" },
    { giris: "Filtreyi temizledim ama su yine gitmiyor", tip: "belirti",
      anlam: "Filtre temiz ve hortum açıkken su hâlâ boşalmıyorsa sıra tahliye pompasına gelir; burası servis sınırıdır.",
      yazi: "camasir-makinesi-su-atmiyor" },
    { giris: "Tek parça yıkarken sıkmıyor (yorgan, halı, kot)", tip: "belirti",
      anlam: "Tek büyük parça dönerken bir tarafta toplanır, makine bunu dengesizlik okur ve devri düşürür; yanına birkaç havlu eklemek yükü dağıtır.",
      yazi: "camasir-makinesi-santrifuj-yapmiyor" },
    { giris: "Hızlanmaya çalışıyor, vazgeçip tekrar deniyor", tip: "belirti",
      anlam: "Klasik dengesizlik davranışıdır, arıza sesi değil; yükü elle dağıtıp sıkma programını tekrarlamak çoğu vakayı bitirir.",
      yazi: "camasir-makinesi-santrifuj-yapmiyor" },
    { giris: "Elektrik kesildi, kapak kilitli kaldı", tip: "belirti",
      anlam: "Kilit elektrikle çözülür; çoğu ön yüklemeli modelde alt kapağın arkasında mekanik acil açma kolu bulunur.",
      yazi: "camasir-makinesi-kapagi-acilmiyor" },
    { giris: "Göstergedeki kilit simgesi sönmüyor", tip: "belirti",
      anlam: "Simge yanarken kapak açılmaz; kazanda kalan su ya da yüksek sıcaklık kilidi tutar. Kapağı zorlamak kilit dilini ve menteşeyi kırar.",
      yazi: "camasir-makinesi-kapagi-acilmiyor" },
    { giris: "Sıkma sırasında yerinden oynuyor / yürüyor", tip: "belirti",
      anlam: "Önce nakliye cıvatası, zemin ve ayak ayarı; hangi noktadan sonra rulman tarafına geçildiği yazıda.",
      yazi: "camasir-makinesi-ses-titresim" },
    { giris: "Tamburdan tak tak sesi geliyor", tip: "belirti",
      anlam: "Yabancı cisim, dengesizlik ve rulman ayrımının nasıl yapılacağı.",
      yazi: "camasir-makinesi-ses-titresim" },
    { giris: "Musluk açık ama tambur dolmuyor", tip: "belirti",
      anlam: "Musluk, su giriş süzgeci ve hortum sırayla aklanır; sonrası servis sınırıdır.",
      yazi: "camasir-makinesi-su-almiyor" },
    { giris: "Program başında uzun süre bekliyor, su yavaş geliyor", tip: "belirti",
      anlam: "Su yeterince hızlı gelmiyorsa kısık musluk ya da kireçlenmiş giriş süzgeci akla gelir.",
      yazi: "camasir-makinesi-su-almiyor" },
    { giris: "Panel hiç yanmıyor, makine ölü", tip: "belirti",
      anlam: "Priz, sigorta ve fiş sırasıyla aklanır; panel hâlâ tepkisizse elektronik kart sınırındasın.",
      yazi: "camasir-makinesi-calismiyor" },
    { giris: "Arkadan, hortum bağlantısından su geliyor", tip: "belirti",
      anlam: "Suyun geldiği yön kaynağı söyler: arkadan gelen su çoğu zaman musluk ve hortum bağlantılarıdır.",
      yazi: "camasir-makinesi-su-kaciriyor" },
    { giris: "Tahliye filtresini hiç temizlemedim, nasıl yapılır", tip: "ayar",
      anlam: "Alt kapaktaki filtrenin 6 adımda güvenle çıkarılması, temizlenmesi ve yerine takılması.",
      yazi: "camasir-makinesi-tahliye-filtresi-temizleme" },
    { giris: "Yıkanan çamaşırlar kokulu çıkıyor", tip: "belirti",
      anlam: "Koku kaynağı çoğu zaman makinenin kendisidir: kapı contası, çekmece, filtre ve kireç sırayla ele alınır.",
      yazi: "camasir-makinesi-kokuyor" },
    { giris: "Çamaşırlarda pas izi çıkıyor", tip: "belirti",
      anlam: "Pas izi içeride kalmış bir metali işaret eder; siyah-gri lekenin adresi ise kapak contası ve kirli tamburdur.",
      yazi: "camasir-makinesi-camasirlarda-leke-birakiyor" },
    { giris: "Yıkama bitti, çekmecede deterjan kaldı", tip: "belirti",
      anlam: "Çoğu zaman su basıncı ya da tıkanmış çekmece kanallarıdır; temizliği kendin yaparsın, giriş valfi servis işidir.",
      yazi: "camasir-makinesi-deterjan-almiyor" },
    { giris: "Yumuşatıcı gözü taşıyor", tip: "ayar",
      anlam: "Taşmanın anatomisi: doğru göz, doğru seviye ve sık yapılan üç yanlış.",
      yazi: "camasir-makinesi-deterjan-cekmecesi-hangi-goz" },
    { giris: "Kurutma süresi eskisinden çok uzadı", tip: "ayar",
      anlam: "İlk durak kapak filtresi, ikinci durak kondenser; hav birikimi hava akışını düşürür.",
      yazi: "kurutma-makinesi-filtre-ve-kondenser-temizligi" },
    { giris: "Tambur dönüyor, hava geliyor ama çamaşır kurumuyor", tip: "belirti",
      anlam: "Makine ısıtır ama nem dışarı atılamıyorsa çamaşır kurumaz; filtre, hazne, yoğuşturucu ve yükleme miktarı bakılır.",
      yazi: "kurutma-makinesi-kurutmuyor" },
    { giris: "Tankı boşalttım ama uyarı gitmiyor", tip: "belirti",
      anlam: "Tankın yuvasına tam oturması, şamandıra ve kondenser tıkanıklığı sırayla kontrol edilir.",
      yazi: "kurutma-makinesi-su-tanki-dolu-uyarisi" },
    { giris: "Elektrik tüketimi birden arttı", tip: "ayar",
      anlam: "Enerjinin çoğu suyu ısıtmaya gider; aynı programda tüketimin belirgin artması bir sinyal olabilir.",
      yazi: "camasir-makinesi-ne-kadar-elektrik-harcar" },
  // ——— 21 Ağu tur-3: tıklama odaklı kod + karar dalgası (12 yazı) ———
  // ⛔ `firin-tamiri-kac-para` ve `televizyon-tamiri-kac-para` BİLEREK BAĞLANMADI:
  //    başlıklarındaki "para" kelimesi kategori sayfasına sızıyor ve YK #35 şart 1'i
  //    ihlal ediyor (build 21 Ağu'da 3 sayfada yakaladı). Mevcut "…kaç para" yazıları da
  //    aynı sebeple bu ağaçta yok — istisna açılmadı. O yazılar /blog/ tarafında yaşıyor.
    { giris: "Arçelik — semboller ve uyarı ışıkları", tip: "kod",
      anlam: "Arçelik'in kendi kılavuzunda E kodu yok; cihaz sembolle konuşuyor — su tankı yanıyor mu yanıp sönüyor mu ayrımı.",
      yazi: "arcelik-kurutma-makinesi-hata-kodlari" },
  ],
  "Bulaşık Makinesi": [
    { giris: "E15 (musluk işareti)", tip: "kod",
      // 🚨 22 Ağu (TARAMA-1): "suyu boşaltmayı kendin yapabilirsin" KALDIRILDI.
      // Bosch'un E15 sayfası: "Sağlığınız ve güvenliğiniz için sorunu evde tek başınıza
      // çözmeyi denememenizi öneririz. Şebeke suyunu kesin ve cihazı kapatın."
      // 📌 `rehber: true` KALDI: yazı hâlâ geçerli bir rehber — ama artık "suyu boşalt"
      // değil, "suyu kes, gözle, not al, servisi ara" adımlarını anlatıyor. Kaldırmak
      // kullanıcıyı rehbersiz bırakırdı; ② katman denetimi de bunu şart koşuyor.
      anlam: "Su koruma sistemi devrede, tabanda su var. Bosch: şebeke suyunu kes, cihazı kapat, servisi ara.",
      yazi: "bosch-bulasik-makinesi-e15-hatasi", rehber: true },
    { giris: "E22", tip: "kod",
      anlam: "İç (taban) filtre tıkalı, su süzülemiyor. Filtreyi çıkarıp temizleyebilirsin.",
      yazi: "bosch-bulasik-makinesi-e22-hatasi", rehber: true },
    { giris: "E24", tip: "kod",
      anlam: "Makine suyu atamıyor; genelde tıkalı filtre ya da bükük tahliye hortumu.",
      yazi: "bosch-bulasik-makinesi-e24-hatasi", rehber: true },
    { giris: "Bosch · Siemens · Profilo · Neff — tüm kodlar", tip: "kod",
      anlam: "E15, E22, E24 ve diğer kodların tek tek karşılığı.",
      yazi: "bosch-bulasik-makinesi-hata-kodlari" },
    { giris: "Marka fark etmeksizin en sık kodlar", tip: "kod",
      anlam: "Arçelik, Beko ve diğer markalarda en sık kodların ortak anlamı.",
      yazi: "bulasik-makinesi-hata-kodlari" },
    // 22 Ağu (YK taraması): yazı kendin-çöz rehberi olarak kaydedildi → `rehber: true`.
    // YK #35 ② katman denetimi bunu ŞART koşuyor; olmadan build DURUR.
    { giris: "Su atmıyor / tabanda su kalıyor", tip: "belirti",
      anlam: "En sık sebep tıkalı filtre ya da pompa; kendin bakabileceğin noktalar var.",
      yazi: "bulasik-makinesi-su-atmiyor", rehber: true },
    { giris: "Su almıyor", tip: "belirti",
      anlam: "Musluk, giriş filtresi ve valf sırayla kontrol edilir.",
      yazi: "bulasik-makinesi-su-almiyor" },
    { giris: "Kurutmuyor / bulaşıklar ıslak çıkıyor", tip: "belirti",
      anlam: "Parlatıcıdan rezistansa 6 olası neden ve hangisini kendin çözebilirsin.",
      yazi: "bulasik-makinesi-kurutmuyor" },
    { giris: "Temiz yıkamıyor", tip: "belirti",
      anlam: "Püskürtme kolu, filtre, kireç ve yerleştirme kaynaklı 6 neden.",
      yazi: "bulasik-makinesi-temiz-yikamiyor", rehber: true },
    { giris: "Kötü koku", tip: "belirti",
      anlam: "Tıkalı filtre, yemek artığı, kireç, kapı contası ve tahliye kaynaklı koku.",
      yazi: "bulasik-makinesi-kokuyor", rehber: true },

  // ——— Boşluk dalgası (20 Ağu 2026, YK — 85-konu taraması) ———
    // 22 Ağu (TARAMA-1): Üreticinin bulaşık listesi BEŞ kod — E01 E02 E06 E07 E26.
    // E03 ve E04 aslında Arçelik KOMBİ kodları (baca sigortası · düşük su basıncı);
    // E05, E08, E09 hiçbir üretici yayınında yok. Eski girişler beşini de sayıyordu.
    { giris: "Arçelik — E01, E02, E06, E07, E26", tip: "kod",
      anlam: "Taşma, su kesik, NTC sensörü, sürekli su alma ve kompresör kodlarının karşılığı.",
      yazi: "arcelik-bulasik-makinesi-hata-kodlari" },
    { giris: "Beko — E01, E02, E06, E07, E26", tip: "kod",
      anlam: "Üreticinin yayımladığı beş kodun karşılığı; hangisinde evde ne yapılır.",
      yazi: "beko-bulasik-makinesi-hata-kodlari" },
    { giris: "Samsung — 4C, 5C, LC, HE", tip: "kod",
      anlam: "4C su temini, 5C tahliye, LC kaçak, HE ısıtıcı demek; özellikle 4C için evde yapılacak kontroller.",
      yazi: "samsung-bulasik-makinesi-hata-kodlari" },
    // 22 Ağu (TARAMA-1): Vestel BULAŞIKTA E kodu KULLANMIYOR — 5 resmî kılavuzda E ile
    // başlayan kod sayısı 0. Tablo F serisi. (E01/E02/E03 Vestel ÇAMAŞIR makinesinin
    // kodları; iki cihazın tablosu karışmış.) Eski giriş dört koddan üçünü uyduruyordu.
    { giris: "Vestel — FF, F2, F1, F3 (E kodu yok)", tip: "kod",
      anlam: "Kılavuzdaki on iki F kodunun anlamı; Vestel yalnız FF ve F2'de evde iş tarif ediyor.",
      yazi: "vestel-bulasik-makinesi-hata-kodlari" },
    { giris: "Siemens — E15 (musluk işareti)", tip: "kod",
      // 🚨 22 Ağu (TARAMA-1): "suyu güvenle boşaltma adımları" ifadesi kaldırıldı; BSH
      // bu kodda evde çözüm denenmesini önermiyor (bkz. bosch-…-e15 kaydındaki not).
      anlam: "Su koruma sistemi devrede, tabanda su var. Üretici: şebeke suyunu kes, cihazı kapat, servisi ara.",
      yazi: "siemens-bulasik-makinesi-e15-hatasi" },
    { giris: "Alttan su kaçırıyor", tip: "belirti",
      anlam: "Sebep çoğu zaman kapı contası, hortum bağlantısı ya da taşma emniyetidir; kendin kontrol edeceklerin belli.",
      yazi: "bulasik-makinesi-su-kaciriyor" },
    { giris: "Programı bitirmiyor / sürekli çalışıyor", tip: "belirti",
      anlam: "Isıtma, su alma-boşaltma döngüsü ya da sensör kaynaklı olabilir; hangi ses normal, ne zaman servis gerekir.",
      yazi: "bulasik-makinesi-programi-bitirmiyor" },
    { giris: "Tableti eritmiyor", tip: "belirti",
      anlam: "Çoğu zaman yükleme hatası, kapağı engelleyen bir parça ya da ısınmayan sudur.",
      yazi: "bulasik-makinesi-tableti-eritmiyor" },
    { giris: "Bardakları bulanık bırakıyor", tip: "belirti",
      anlam: "Tuz-parlatıcı ayarı, kireç ya da cam korozyonu olabilir; hangisi düzelir, hangisi kalıcı.",
      yazi: "bulasik-makinesi-bardaklari-bulanik-birakiyor" },
    { giris: "Tuz lambası sönmüyor", tip: "belirti",
      anlam: "Çoğu zaman sensör gecikmesi ya da haznede kalıplaşan tuzdur; tuzun doğru konuluşu ve lambanın mantığı.",
      yazi: "bulasik-makinesi-tuz-lambasi-sonmuyor" },
    { giris: "Filtre nasıl temizlenir", tip: "ayar",
      anlam: "Alt filtreyi elle çıkarıp temizlemek 10 dakikalık iş; püskürtme kolu delikleriyle birlikte adım adım.",
      yazi: "bulasik-makinesi-filtresi-nasil-temizlenir" },
    { giris: "Tuz, sertlik ve parlatıcı ayarı", tip: "ayar",
      anlam: "Beyaz lekeli bardak ve mat tabakların çözümü deterjan değil: tuz, sertlik ayarı ve parlatıcı kademesi.",
      yazi: "bulasik-makinesi-tuzu-ve-parlatici-ayari" },
    { giris: "Makineye neler konmaz", tip: "ayar",
      anlam: "Teflon, ahşap, kristal, döküm, alüminyum ve keskin bıçak; girmemesi gerekenler ve sebepleri.",
      yazi: "bulasik-makinesine-neler-konmaz" },
    { giris: "Ne kadar elektrik ve su harcar", tip: "ayar",
      anlam: "Program başına kWh ve litre değerleri, elde yıkamayla litre kıyası ve eko programın uzun-ama-az-harcayan gerçeği.",
      yazi: "bulasik-makinesi-ne-kadar-elektrik-harcar" },

  // ——— Kayıt genişletmesi (21 Ağu 2026, YK #80 · hedef 200+) ———
    { giris: "Tabaklarda yemek kalıntısı kalıyor", tip: "belirti",
      anlam: "Püskürtme kolu delikleri tıkalıysa su bulaşıklara ulaşmaz; kollar ve taban filtresi aletsiz temizlenir.",
      yazi: "bulasik-makinesi-temiz-yikamiyor" },
    { giris: "Üst sepet iyi yıkanmıyor", tip: "belirti",
      anlam: "Üst kol dönmüyor ya da uzun saplı bir parça kolu kilitliyor olabilir; kolu elinle çevirip serbest döndüğünü doğrula.",
      yazi: "bulasik-makinesi-temiz-yikamiyor" },
    { giris: "Program bitti ama içinde su kalıyor", tip: "belirti",
      anlam: "İlk bakılacak yer taban filtresi ve altındaki pompa kapağıdır; cam kırığı ya da etiket pervaneyi kilitleyebilir.",
      yazi: "bulasik-makinesi-su-atmiyor" },
    { giris: "Pompadan ses geliyor ama su gitmiyor", tip: "belirti",
      anlam: "Filtre ve pompa kapağı temizken ses gelip su gitmiyorsa işaret tahliye pompasını gösterir; bu servis işidir.",
      yazi: "bulasik-makinesi-su-atmiyor" },
    { giris: "Musluk açık ama makine dolmuyor", tip: "belirti",
      anlam: "Musluk-hortum bağlantısındaki küçük süzgeç kireç ve tortuyla tıkanmış olabilir; temizliğini kendin yaparsın.",
      yazi: "bulasik-makinesi-su-almiyor" },
    { giris: "Kapağı kapattım ama program başlamıyor", tip: "belirti",
      anlam: "Kapak klik sesiyle tam kapanmadıysa program başlamaz; çocuk kilidi de kontrol edilir.",
      yazi: "bulasik-makinesi-su-almiyor" },
    { giris: "Plastik kaplar hiç kurumuyor", tip: "belirti",
      anlam: "Plastik ısı tutmaz, en son o kurur; üst sepete al ve program bitince kapağı arala.",
      yazi: "bulasik-makinesi-kurutmuyor" },
    { giris: "Eko programda bulaşıklar nemli kalıyor", tip: "belirti",
      anlam: "Eco ve hızlı programlar kurutma aşamasını kısar ya da atlar; yoğun veya ekstra kurutma seçeneği gerekir.",
      yazi: "bulasik-makinesi-kurutmuyor" },
    { giris: "Lağım kokusu geliyor", tip: "belirti",
      anlam: "Keskin lağım kokusu genelde tahliye hortumundaki biyofilm ya da tıkanıklıktır; iç temizlik çözmezse servis.",
      yazi: "bulasik-makinesi-kokuyor" },
    { giris: "Kapı contasında küf var", tip: "belirti",
      anlam: "Contanın kıvrımlarında kalan artık ve nem küf yapar; nemli bezle silmek işin ev tarafıdır.",
      yazi: "bulasik-makinesi-kokuyor" },
    { giris: "Süre göstergesi ilerlemiyor", tip: "belirti",
      anlam: "Isıtma yetişmediğinde program bekler ve kalan süre uzayabilir; hangi ses normal, nerede servis başlar.",
      yazi: "bulasik-makinesi-programi-bitirmiyor" },
    { giris: "Deterjan bölmesi açılmıyor", tip: "belirti",
      anlam: "En sık sebep bölmenin önünü kapatan bir tabak ya da uzun saplı parçadır; ıslak bölmede tablet de yapışır.",
      yazi: "bulasik-makinesi-tableti-eritmiyor" },
    { giris: "Bardaklarda su damlası izleri kalıyor", tip: "belirti",
      anlam: "Nokta nokta damla izi düşük parlatıcı dozunu, gökkuşağı renkli yağlımsı iz ise fazla dozu gösterir.",
      yazi: "bulasik-makinesi-bardaklari-bulanik-birakiyor" },
    { giris: "Makinenin altında su birikti", tip: "belirti",
      anlam: "Önce su mu köpük mü ayrımı yapılır; kapı contası, görünür hortum bağlantıları ve taşma emniyeti sırayla bakılır.",
      yazi: "bulasik-makinesi-su-kaciriyor" },
  // ——— 21 Ağu boşluk dalgası tur-2 (25 yeni yazı) ———
    { giris: "Arçelik · Beko — E01", tip: "kod",
      anlam: "Su güvenliği (taşma koruması) devrede; taban suyunu boşaltma ve kaçak arama sırası belli.",
      yazi: "arcelik-bulasik-makinesi-e01-hatasi" },
    { giris: "Beko — E01 (taşma koruması)", tip: "kod",
      anlam: "Şamandıra kalkmış demek; makineyi eğip tabandaki suyu boşaltmak ilk adım.",
      yazi: "beko-bulasik-makinesi-e01-hatasi" },
    { giris: "Samsung — 4C", tip: "kod",
      anlam: "Makine su alamıyor: musluk, giriş hortumu ve filtre elemesi evde yapılıyor.",
      yazi: "samsung-bulasik-makinesi-4c-hatasi" },
    { giris: "Eko program neden uzun sürüyor", tip: "ayar",
      anlam: "Uzun süre arıza değil, tasarımın kendisi; suyu yavaş ısıtıp az enerjiyle yıkıyor.",
      yazi: "bulasik-makinesi-eko-program-neden-uzun" },
  // ——— 21 Ağu tur-3: tıklama odaklı kod + karar dalgası (12 yazı) ———
  // ⛔ `firin-tamiri-kac-para` ve `televizyon-tamiri-kac-para` BİLEREK BAĞLANMADI:
  //    başlıklarındaki "para" kelimesi kategori sayfasına sızıyor ve YK #35 şart 1'i
  //    ihlal ediyor (build 21 Ağu'da 3 sayfada yakaladı). Mevcut "…kaç para" yazıları da
  //    aynı sebeple bu ağaçta yok — istisna açılmadı. O yazılar /blog/ tarafında yaşıyor.
    { giris: "Siemens — E07…E27", tip: "kod",
      anlam: "Siemens ve Bosch aynı kod dilini konuşuyor, panel farklı; hangi kod evde çözülür belli.",
      yazi: "siemens-bulasik-makinesi-hata-kodlari" },
  ],

  "Kombi / Termosifon": [
    { giris: "Vaillant — F.22, F.28, F.29, F.75", tip: "kod",
      anlam: "Vaillant panelindeki F kodlarının tam listesi ve karşılıkları.",
      yazi: "vaillant-kombi-ariza-kodlari" },
    // 22 Ağu (TARAMA-1): DemirDöküm'ün İKİ kod ailesi var ve yazı ikisini karıştırmıştı.
    // Nitromix/ademiX → noktalı (Vaillant platformu) · Atron/Nitron → noktasız F04/F05/F10.
    // F.04 ve F.05'in anlamı TERSTİ: F04 ateşleme (fan değil), F05 baca (NTC değil).
    { giris: "DemirDöküm — F.22 · F.28 · F10 · F04 (iki aile)", tip: "kod",
      anlam: "Noktalı ve noktasız iki kod ailesi; hangi seride hangisi geçerli ve karşılıkları.",
      yazi: "demirdokum-kombi-ariza-kodlari" },
    // 22 Ağu 2026 (TARAMA-1): "E04" ÇIKARILDI — Baymak'ta böyle bir kod yok.
    // Gerçek düşük su basıncı kodu F37 (Lunatec/Startec'te H.02.07).
    { giris: "Baymak — E01, E05, F37", tip: "kod",
      anlam: "Ateşleme, fan ve düşük su basıncı kodlarının anlamı.",
      yazi: "baymak-kombi-ariza-kodlari" },
    { giris: "Marka fark etmeksizin en sık kodlar", tip: "kod",
      anlam: "Markası listede yoksa buradan bak; hangi kodda güvenle ne yapabilirsin.",
      yazi: "kombi-ariza-kodlari" },
    { giris: "Yanmıyor / ateşleme yapmıyor", tip: "belirti",
      anlam: "Gaz, su basıncı, ateşleme elektrodu ve fan sırasıyla değerlendirilir.",
      yazi: "kombi-yanmiyor" },
    { giris: "Su basıncı sürekli düşüyor", tip: "belirti",
      anlam: "Tesisat kaçağı, genleşme tankı ve emniyet ventili ayrımı.",
      yazi: "kombi-basinc-dusuyor" },
    { giris: "Sıcak su vermiyor (ısıtma çalışıyor)", tip: "belirti",
      anlam: "Plakalı eşanjör kireci, 3 yollu vana ve akış sensörü nedenleri.",
      yazi: "kombi-sicak-su-vermiyor" },
    { giris: "Yazın kapatılır mı, yaz modu nedir", tip: "ayar",
      anlam: "Yaz modu ne yapar, uzun süre kapalı kombide pompa sıkışması riski nedir.",
      yazi: "kombi-yazin-kapatilir-mi" },

  // ——— Kayıt genişletmesi (21 Ağu 2026, YK #80 · hedef 200+) ———
    { giris: "Ekranda düşük su basıncı kodu var", tip: "kod",
      // 22 Ağu 2026 (TARAMA-1) — ÇİFTE TAKAS düzeltildi: F.37 Baymak'ın kodudur,
      // DemirDöküm'e yazılmıştı; Baymak'a ise var olmayan E04 verilmişti.
      // DemirDöküm'ün ikinci platformunda (Atron/Nitron) karşılık F10.
      anlam: "Her markanın en sık kodu budur (Vaillant F.22, DemirDöküm F.22, Baymak F37) ve doldurma musluğuyla güvenle çözülür.",
      yazi: "kombi-ariza-kodlari" },
    { giris: "Sürekli su basmam gerekiyor", tip: "belirti",
      anlam: "Su eklemek geçici çözümdür; kaynak tesisat kaçağı, genleşme tankı ya da emniyet ventili olabilir.",
      yazi: "kombi-basinc-dusuyor" },
    { giris: "Kombinin dış tahliye borusundan su damlıyor", tip: "belirti",
      anlam: "Tahliyeden gelen damlama emniyet ventili ya da genleşme tankı şüphesini gündeme getirir.",
      yazi: "kombi-basinc-dusuyor" },
    { giris: "Isınınca basınç yükseliyor, soğuyunca düşüyor", tip: "belirti",
      anlam: "Isınınca aşırı yükselip ventilden taşan basınç genellikle genleşme tankı arızasına işaret eder.",
      yazi: "kombi-basinc-dusuyor" },
    { giris: "Musluktan ılık su geliyor", tip: "belirti",
      anlam: "İlk iki şüpheli plakalı eşanjörün kireçlenmesi ve musluk ucundaki tıkalı süzgeçtir.",
      yazi: "kombi-sicak-su-vermiyor" },
    { giris: "Petekler ısınıyor ama su ısınmıyor", tip: "belirti",
      anlam: "Isıtma çalışırken sıcak su yoksa sorun sıcak su devresindedir: eşanjör, 3 yollu vana ya da akış sensörü.",
      yazi: "kombi-sicak-su-vermiyor" },
    { giris: "Petekler de soğuk, sıcak su da yok", tip: "belirti",
      anlam: "İkisi birden yoksa sorun sıcak su tarafında değil, kombinin yanmasındadır.",
      yazi: "kombi-yanmiyor" },
    { giris: "Reset'e bastım ama kombi yine kilitleniyor", tip: "belirti",
      anlam: "Gaz açık, basınç doğru ve reset tutmuyorsa ateşleme elektrodu ya da gaz valfi şüphesi başlar.",
      yazi: "kombi-yanmiyor" },
    { giris: "Kışın ilk çalıştırmada kombi açılmadı", tip: "belirti",
      anlam: "Aylarca hiç çalışmayan kombide sirkülasyon pompası sıkışabilir, contalar kuruyabilir.",
      yazi: "kombi-yazin-kapatilir-mi" },
    { giris: "Tatile giderken kombi ne yapılmalı", tip: "ayar",
      anlam: "Kısa tatilde yaz modu yeter; uzun tatilde gaz vanası kapatılır ve dönüşte basınç kontrol edilir.",
      yazi: "kombi-yazin-kapatilir-mi" },
  ],

  "Buzdolabı": [
    { giris: "Çalışıyor ama soğutmuyor", tip: "belirti",
      anlam: "6 olası neden ve servis çağırmadan önce kendin bakabileceğin noktalar.",
      yazi: "buzdolabi-sogutmuyor-nedenleri" },
    { giris: "Buzluk soğuk, alt bölme soğumuyor (no-frost)", tip: "belirti",
      anlam: "No-frost modellerin klasik sebebi fan ve buz çözme tarafındadır.",
      yazi: "no-frost-buzdolabi-alt-bolme-sogutmuyor" },
    { giris: "Buz tutuyor / buzlanma yapıyor", tip: "belirti",
      anlam: "Kapı contası, buz çözme arızası, tıkalı tahliye kanalı ve kapı alışkanlıkları.",
      yazi: "buzdolabi-buzlanma-yapiyor", rehber: true },
    { giris: "Altında ya da sebze gözünde su birikiyor", tip: "belirti",
      anlam: "En sık sebep tıkalı tahliye deliğidir.",
      yazi: "buzdolabi-altinda-su-birikiyor" },
    { giris: "Ses yapıyor (vızıltı, tıkırtı)", tip: "belirti",
      anlam: "Hangi ses normal, hangisi arıza işareti — sesten ayrım tablosu.",
      yazi: "buzdolabi-ses-yapiyor" },
    { giris: "Kaç dereceye ayarlanmalı", tip: "ayar",
      anlam: "Soğutucu +4°C, dondurucu -18°C; yaz-kış ayar ve 1-5 kademeli düğme karşılığı.",
      yazi: "buzdolabi-kac-derece-olmali" },
    { giris: "Derin dondurucu kaç derece olmalı", tip: "ayar",
      anlam: "-18°C kuralı, şoklama ne zaman açılır, kesintide gıda kaç saat dayanır.",
      yazi: "derin-dondurucu-kac-derece-olmali" },

  // ——— Boşluk dalgası (20 Ağu 2026, YK — 85-konu taraması) ———
    { giris: "Marka fark etmeksizin ekran kodları", tip: "kod",
      anlam: "No-frost modellerde kod mantığı; Beko E0-E4 kodları ile Vestel SR/LV uyarıları, servis noktası.",
      yazi: "buzdolabi-hata-kodlari" },
    { giris: "Samsung — 5E, 6E, 22E, 84E, OF OF", tip: "kod",
      anlam: "Kodların doğrulanmış anlamları ve OF OF demo modu tuzağı.",
      yazi: "samsung-buzdolabi-hata-kodlari" },
    { giris: "Motor çalışmıyor / tık sesi geliyor", tip: "belirti",
      anlam: "Lamba yanıyor ama motor kalkmıyorsa elektrik, başlatma rölesi ya da kompresör; tık döngüsü ne anlatır.",
      yazi: "buzdolabi-motoru-calismiyor" },
    { giris: "Çok soğutuyor, sebzeler donuyor", tip: "belirti",
      anlam: "Çoğu zaman ayar kademesi, arka duvara değen yiyecek ya da kapalı hava kanalıdır.",
      yazi: "buzdolabi-cok-sogutuyor" },
    { giris: "Gaz kaçağı şüphesi", tip: "belirti",
      anlam: "Gerçek belirtiler soğutma kaybı, hiç durmayan motor ve borulardaki yağlı iz; koku çoğu zaman başka şeydir.",
      yazi: "buzdolabi-gaz-kacagi-nasil-anlasilir" },
    { giris: "Kapısı tam kapanmıyor", tip: "belirti",
      anlam: "Çoğu zaman conta, denge ayağı ya da taşan raflardır; kâğıt testiyle contayı yokla.",
      yazi: "buzdolabi-kapisi-tam-kapanmiyor" },
    { giris: "Kapı contası bakımı", tip: "ayar",
      anlam: "Dolap çok çalışıyor, içi terliyorsa şüpheli conta: kâğıt testi ve ılık su-sabunla temizlik, 15 dakikalık iş.",
      yazi: "buzdolabi-kapi-contasi-bakimi" },
    { giris: "Nasıl temizlenir (sirke + karbonat)", tip: "ayar",
      anlam: "Kimyasalsız temizliğin adım adım yolu: raflar, conta ve arka ızgara.",
      yazi: "buzdolabi-nasil-temizlenir" },
    { giris: "Raf düzeni ve duvar mesafesi", tip: "ayar",
      anlam: "Süt neden kapı rafına konmaz, et hangi rafta durur, dolap duvardan kaç santim açık olmalı.",
      yazi: "buzdolabi-raf-duzeni-ve-duvar-mesafesi" },
    { giris: "Ne kadar elektrik harcar", tip: "ayar",
      anlam: "Günde ve yılda kaç kWh; enerji etiketi okuma ve contadan sıcak yemeğe tüketimi artıran hatalar.",
      yazi: "buzdolabi-ne-kadar-elektrik-harcar" },
    { giris: "Derin dondurucuda kalın buz — buz çözme", tip: "ayar",
      anlam: "Yiyecekleri soğuk zincirde koruyarak, sivri alet kullanmadan güvenli buz çözme uygulaması.",
      yazi: "derin-dondurucu-buz-cozme" },

  // ——— Kayıt genişletmesi (21 Ağu 2026, YK #80 · hedef 200+) ———
    { giris: "Hiç durmuyor, sürekli çalışıyor", tip: "belirti",
      anlam: "Uzun çalışmayla hiç durmama farkı; havalandırma boşluğu, kapı contası, arka ızgara tozu ve derece ayarı sırayla elenir.",
      yazi: "buzdolabi-hic-durmuyor" },
    { giris: "Derin dondurucu dondurmuyor", tip: "belirti",
      anlam: "Conta, buz tutması, termostat, hava dolaşımı ve fan; ilk üçü evde anlaşılır, kompresör ve gaz tarafı servise kalır.",
      yazi: "derin-dondurucu-dondurmuyor" },
    { giris: "Buzdolabım eski, değiştirsem mi tamir mi ettirsem?", tip: "belirti",
      anlam: "Yıllık kWh farkı üzerinden amorti hesabı, 15 yaş eşiği ve kararın üç soruluk çerçevesi.",
      yazi: "eski-buzdolabini-degistirmek-mantikli-mi" },
    { giris: "Buzluk soğuk ama dolap ılık", tip: "belirti",
      anlam: "No-frost'ta soğuk hava buzluktan fanla dolaba üflenir; fan ya da buz çözme arızalanırsa buzluk soğur, dolap ılık kalır.",
      yazi: "buzdolabi-sogutmuyor-nedenleri" },
    { giris: "Yiyecekler bozuluyor", tip: "belirti",
      anlam: "Cihaz çalışıyor ama soğutamıyorsa 6 olası neden var; ayar, conta ve arka toz kendin elenir.",
      yazi: "buzdolabi-sogutmuyor-nedenleri" },
    { giris: "Yeni taşındık, dolap soğutmuyor", tip: "belirti",
      anlam: "Yatık taşınan dolapta kompresör yağı borulara kaçmış olabilir; fişe takmadan önce birkaç saat dik bekletmek gerekir.",
      yazi: "buzdolabi-sogutmuyor-nedenleri" },
    { giris: "Gece uğulduyor", tip: "belirti",
      anlam: "Uğultudan tiz çığlığa dönen ses no-frost iç fan motorunun yatağını işaret eder; ses arttıkça fan durabilir.",
      yazi: "buzdolabi-ses-yapiyor" },
    { giris: "Fokurdama sesi geliyor", tip: "belirti",
      anlam: "Fokurtu ve şırıltı normaldir: soğutucu gazın borularda dolaşma sesidir, gelir gider.",
      yazi: "buzdolabi-ses-yapiyor" },
    { giris: "Sadece sebzelik donduruyor", tip: "belirti",
      anlam: "Sebzelik soğuk havanın indiği bölgeye yakındır; ayarı bir kademe düşürüp yiyecekleri arka duvardan ayırmak çoğu vakada yeter.",
      yazi: "buzdolabi-cok-sogutuyor" },
    { giris: "Elektrik kesintisinden sonra çalışmadı", tip: "belirti",
      anlam: "Bazı modellerde motor durduktan hemen sonra kalkmaz; basınç dengelenene kadar birkaç dakikalık gecikme normaldir.",
      yazi: "buzdolabi-motoru-calismiyor" },
    { giris: "Kapı kendiliğinden açılıyor", tip: "belirti",
      anlam: "Cihaz öne eğikse bırakılan kapı aralanır; ön denge ayaklarını çevirmek kullanıcının yapabileceği bir iştir.",
      yazi: "buzdolabi-kapisi-tam-kapanmiyor" },
    { giris: "Mutfak zeminine su damlıyor", tip: "belirti",
      anlam: "Arka alttaki tahliye tavası kaymış ya da çatlamış olabilir; önce arka iç duvardaki tahliye deliğine bakılır.",
      yazi: "buzdolabi-altinda-su-birikiyor" },
    { giris: "Soğutma yavaş yavaş zayıfladı", tip: "belirti",
      anlam: "Kademeli soğutma kaybı gaz kaçağının en tutarlı işaretidir — ama önce conta, havalandırma ve ayar elenmelidir.",
      yazi: "buzdolabi-gaz-kacagi-nasil-anlasilir" },
    { giris: "Ekranda OF OF yazıyor", tip: "kod",
      anlam: "Panel çalışıyor ama soğutma yoksa bu çoğu zaman arıza değil mağaza/demo modudur; çıkış da panelden yapılır.",
      yazi: "samsung-buzdolabi-hata-kodlari" },
    { giris: "İçinde kötü koku var", tip: "ayar",
      anlam: "Sirke ve karbonatla kimyasalsız temizliğin adımları; koku sürerse çekmece altı ve tahliye kanalı bakılır.",
      yazi: "buzdolabi-nasil-temizlenir" },
    { giris: "Elektrik kesildi, dondurucudakiler ne kadar dayanır", tip: "ayar",
      anlam: "Kapı hiç açılmazsa dolu dondurucu yaklaşık 48, yarı dolu yaklaşık 24 saat güvenli tutar; kural kapıyı açmamaktır.",
      yazi: "derin-dondurucu-kac-derece-olmali" },
    { giris: "Conta yapış yapış olmuş, kararmış", tip: "ayar",
      anlam: "Kâğıt testiyle kontrol, ılık su-sabunla temizlik ve katlanan bölümü düzeltme 15 dakikalık kullanıcı işidir.",
      yazi: "buzdolabi-kapi-contasi-bakimi" },
    { giris: "Tatile çıkıyorum, fişini çekeyim mi", tip: "ayar",
      anlam: "Kısa tatilde çekilmez, tatil modu ya da ekonomik kademe kullanılır; aylarca boş kalacaksa boşalt, temizle, kapıyı aralık bırak.",
      yazi: "tatile-cikarken-buzdolabi-ve-cihazlar" },
  // ——— 21 Ağu boşluk dalgası tur-2 (25 yeni yazı) ———
    { giris: "Arçelik — E, F, S ve D kodları", tip: "kod",
      anlam: "Arçelik iki ayrı kod şeması kullanıyor; önce hangisiyle konuştuğunu ayırt ediyorsun.",
      yazi: "arcelik-buzdolabi-hata-kodlari" },
    { giris: "Beko — E0, E1, E4", tip: "kod",
      anlam: "Üçü de aynı defrost (buz çözme) hattının farklı durakları; evde buz çözdürme adımı dahil.",
      yazi: "beko-buzdolabi-hata-kodlari" },
    { giris: "Bosch — alarm mı, kod mu", tip: "kod",
      anlam: "Bosch buzdolabı çoğu zaman kodla değil alarmla konuşur; tatil modu en sık karışan durum.",
      yazi: "bosch-buzdolabi-hata-kodlari" },
    { giris: "LG — Er FF, rF, CF, IF, dH", tip: "kod",
      anlam: "İki harfli kod doğrudan parçayı söylüyor; fan kodlarının arkasında çoğu zaman buz var.",
      yazi: "lg-buzdolabi-hata-kodlari" },
    { giris: "Buz yapmıyor / buzmatik boş", tip: "belirti",
      anlam: "Su hattı, buzluk sıcaklığı ve buzmatik kolu sırasıyla kontrol ediliyor.",
      yazi: "buzdolabi-buz-yapmiyor" },
    { giris: "Yazın kaç dereceye alınmalı", tip: "ayar",
      anlam: "Sıcak aylarda doğru ayar ve duvar mesafesi; yanlış ayar hem soğutmayı hem tüketimi bozuyor.",
      yazi: "buzdolabi-yaz-ayari" },
  // ——— 21 Ağu tur-3: tıklama odaklı kod + karar dalgası (12 yazı) ———
  // ⛔ `firin-tamiri-kac-para` ve `televizyon-tamiri-kac-para` BİLEREK BAĞLANMADI:
  //    başlıklarındaki "para" kelimesi kategori sayfasına sızıyor ve YK #35 şart 1'i
  //    ihlal ediyor (build 21 Ağu'da 3 sayfada yakaladı). Mevcut "…kaç para" yazıları da
  //    aynı sebeple bu ağaçta yok — istisna açılmadı. O yazılar /blog/ tarafında yaşıyor.
    { giris: "Gaz bitti mi, kaçak mı", tip: "belirti",
      anlam: "Buzdolabı kapalı devredir, gaz kullanımla azalmaz; azaldıysa kaçak var ve kaçak bulunmadan dolum kalıcı olmaz.",
      yazi: "buzdolabi-gaz-dolumu" },
  ],

  "Klima": [
    { giris: "Az üflüyor / hava akışı zayıf", tip: "belirti",
      anlam: "En sık sebep kirli filtredir; filtreyi kendin temizleyebilirsin.",
      yazi: "klima-filtresi-temizleme", rehber: true },
    { giris: "Soğutmuyor", tip: "belirti",
      anlam: "Kirli filtreden gaz kaçağına kadar 6 olası neden ve ayrım yöntemi.",
      yazi: "klima-sogutmuyor-nedenleri" },
    { giris: "Hiç açılmıyor / çalışmıyor", tip: "belirti",
      anlam: "Elektrik, kumanda, kapasitör ve elektronik kart kaynaklı nedenler.",
      yazi: "klima-calismiyor" },
    { giris: "İç ünite su damlatıyor", tip: "belirti",
      anlam: "En sık sebep tıkalı tahliye hattıdır.",
      yazi: "klima-su-damlatiyor" },
    { giris: "Küf, rutubet ya da yanık kokusu", tip: "belirti",
      anlam: "Hangi koku neyin işareti; kendin ne yapabilirsin, ne zaman servis gerekir.",
      yazi: "klima-koku-yapiyor" },

  // ——— Boşluk dalgası (20 Ağu 2026, YK — 85-konu taraması) ———
    { giris: "Vestel · Arçelik · Daikin — kod okuma mantığı", tip: "kod",
      anlam: "Split klimalarda kod nasıl okunur; üç markada üreticinin kendi kılavuzuyla doğrulanabilen karşılıklar ve servis sınırı.",
      yazi: "klima-ariza-kodlari" },
    { giris: "Dış ünite temizliği", tip: "ayar",
      anlam: "Sökmeden, dışarıdan temizliğin yolu; hortumla yıkamanın neden yasak olduğu ve yükseklik uyarısı.",
      yazi: "klima-dis-unite-temizligi" },

  // ——— Kayıt genişletmesi (21 Ağu 2026, YK #80 · hedef 200+) ———
    { giris: "Saatte ne kadar elektrik harcar", tip: "ayar",
      anlam: "Kapasiteye göre tipik saatlik tüketim, inverter farkı ve tüketimi şişiren beş etken.",
      yazi: "klima-saatte-ne-kadar-elektrik-harcar" },
    { giris: "Ekran yok, ön paneldeki ışıklar yanıp sönüyor", tip: "kod",
      anlam: "Ekransız modellerde arıza bildirimi ışıkların yanıp sönme düzeniyle yapılır; düzen videoya alınıp kılavuz tablosuyla karşılaştırılır.",
      yazi: "klima-ariza-kodlari" },
    { giris: "Elektrik kesintisinden sonra klima çalışmıyor", tip: "belirti",
      anlam: "Birçok klima kesinti sonrası kendini birkaç dakika koruma modunda bekletir; süre dolduğu hâlde açılmıyorsa şalter, kumanda ve kod sırayla bakılır.",
      yazi: "klima-ariza-kodlari" },
    { giris: "Klima çalışıyor ama oda serinlemiyor", tip: "belirti",
      anlam: "Hava üflediği hâlde serinlik yoksa filtre, ayar, dış ünite ve termostat sırayla değerlendirilir.",
      yazi: "klima-sogutmuyor-nedenleri" },
    { giris: "Dışarısı sıcakken hiç soğutmuyor", tip: "belirti",
      anlam: "Dışarı soğuk hava hiç gelmiyorsa gaz ya da kompresör şüphesi öne çıkar; öncesinde dış ünitenin önü açılır.",
      yazi: "klima-sogutmuyor-nedenleri" },
    { giris: "Filtreyi temizledim, yine soğutmuyor", tip: "belirti",
      anlam: "Filtre temiz ve ayarlar doğruyken soğutma dönmüyorsa iş gaz, kompresör ya da dış ünite tarafına geçer.",
      yazi: "klima-sogutmuyor-nedenleri" },
    { giris: "İç ünite çalışıyor, dış ünite dönmüyor", tip: "belirti",
      anlam: "En sık sebep dış ünitedeki marş kapasitörünün zayıflamasıdır; kompresör mırıldanır ama dönmez.",
      yazi: "klima-calismiyor" },
    { giris: "Kumanda ekranı yanıyor ama klima açılmıyor", tip: "belirti",
      anlam: "Kumanda ve elektrik sağlamken komut alınmıyorsa iç ünitenin elektronik kartı ya da alıcı sensörü şüphelenilir.",
      yazi: "klima-calismiyor" },
    { giris: "Klimanın sigortası tekrar tekrar atıyor", tip: "belirti",
      anlam: "Kaldırdıkça yeniden atan sigorta elektrik tarafında arıza demektir; zorlanmaz, servis işidir.",
      yazi: "klima-calismiyor" },
    { giris: "İç üniteden su akıyor", tip: "belirti",
      anlam: "Yoğuşma suyu dışarı atılamayınca iç üniteden taşar; ilk bakılacak yer tahliye hattı ve hortumun dış ucudur.",
      yazi: "klima-su-damlatiyor" },
    { giris: "İç ünite buz tutuyor", tip: "belirti",
      anlam: "Buzlanmanın arkasında kirli filtre ya da gaz azlığı vardır; eriyen buz tavayı taşırıp damlamaya döner.",
      yazi: "klima-su-damlatiyor" },
    { giris: "Açınca yanık ya da plastik kokusu geliyor", tip: "belirti",
      anlam: "Bu koku küf değil elektrik uyarısıdır: cihaz kapatılır, enerjisi kesilir ve kendin açılmadan servis çağrılır.",
      yazi: "klima-koku-yapiyor" },
    { giris: "Dış ünite ses yapıyor, titriyor", tip: "belirti",
      anlam: "Metalik sürtme, tıkırtı ya da güçlü titreşimde klima kapatılır; ünitenin oturması ve ayakları gözle kontrol edilir.",
      yazi: "klima-dis-unite-temizligi" },
    { giris: "Dış üniteyi hortumla yıkayabilir miyim", tip: "ayar",
      anlam: "Hayır: gövdede elektronik kart ve elektrik bağlantısı var, kullanıcı temizliği fırça-süpürge-nemli bezle sınırlıdır.",
      yazi: "klima-dis-unite-temizligi" },
  // ——— 21 Ağu boşluk dalgası tur-2 (25 yeni yazı) ———
    // 22 Ağu (TARAMA-1): "üç kod dili" çerçevesi uydurma bloklar üzerine kuruluydu.
    // E ve P serisi Arçelik'in hiçbir yayınında yok; tek tablo CH serisi (34 kod).
    { giris: "Arçelik — CH serisi (34 kod)", tip: "kod",
      anlam: "Arçelik'in yayımladığı tek tablo CH'dir; E ve P listeleri markaya ait değil.",
      yazi: "arcelik-klima-hata-kodlari" },
    { giris: "Çalışıyor ama iç ünite üflemiyor", tip: "belirti",
      anlam: "Fan motoru, kanat ayarı ve filtre tıkanması ayrımı; evde bakılacaklar sırayla.",
      yazi: "klima-fan-donmuyor" },
    { giris: "Kumanda çalışmıyor", tip: "belirti",
      anlam: "Telefon kamerasıyla iki dakikada kumanda testi: sorun kumandada mı, iç ünitede mi.",
      yazi: "klima-kumandasi-calismiyor" },
  // ——— 21 Ağu tur-3: tıklama odaklı kod + karar dalgası (12 yazı) ———
  // ⛔ `firin-tamiri-kac-para` ve `televizyon-tamiri-kac-para` BİLEREK BAĞLANMADI:
  //    başlıklarındaki "para" kelimesi kategori sayfasına sızıyor ve YK #35 şart 1'i
  //    ihlal ediyor (build 21 Ağu'da 3 sayfada yakaladı). Mevcut "…kaç para" yazıları da
  //    aynı sebeple bu ağaçta yok — istisna açılmadı. O yazılar /blog/ tarafında yaşıyor.
    { giris: "Daikin — U, E, A, F, H, J, L kodları", tip: "kod",
      anlam: "İlk harf üniteyi söylüyor: A/C iç ünite, E/F/H/J/L dış ünite, U sistem. Kodu ekranda okuma yolu dahil.",
      yazi: "daikin-klima-hata-kodlari" },
    { giris: "Vestel — Er + iki hane", tip: "kod",
      anlam: "Güncel inverter kılavuzlarında format Er01, Er11, Er13; DF, AE, HL ise arıza değil koruma mesajı.",
      yazi: "vestel-klima-hata-kodlari" },
    { giris: "Samsung — C1, E5, E6, E7 · CF, CL, dF", tip: "kod",
      anlam: "CF, CL ve dF arıza değil hatırlatıcı; C1 yanındaki sayı asıl arızayı söylüyor.",
      yazi: "samsung-klima-hata-kodlari" },
    { giris: "Montaj · söküm-takma nelerden oluşur", tip: "ayar",
      anlam: "Taşınmada söküm ve takma iki ayrı iş; gaz toplanmazsa ne kaybediliyor ve kötü montaj garantiyi nasıl etkiliyor.",
      yazi: "klima-montaj-sokum-takma" },
  ],

  "Fırın / Ocak / Aspiratör": [
    { giris: "Ocak ateşleme yapmıyor / kıvılcım yok", tip: "belirti",
      anlam: "Çakmak çakıyor ama ocak yanmıyorsa önce başlık temizliği, buji ve gaz akışı.",
      yazi: "ocak-atesleme-yapmiyor" },
    { giris: "Ateşleme bujisi değişmeli mi", tip: "belirti",
      anlam: "Bujiyi değiştirmeden önce denenecek 3 şey ve bu işin neden servis işi olduğu.",
      yazi: "ocak-atesleme-bujisi-degisimi" },
    { giris: "Fırın ısınmıyor ya da geç ısınıyor", tip: "belirti",
      anlam: "Rezistans, termostat, fan ve kart ayrımı; servis çağırmadan önce kontroller.",
      yazi: "firin-isinmiyor" },
    { giris: "Aspiratör çekmiyor ya da koku yapıyor", tip: "belirti",
      anlam: "Bu arıza için kendin-çöz adımı yayınlamadık; ölçüm ve yetki isteyen bir iş." },

  // ——— Boşluk dalgası (20 Ağu 2026, YK — 85-konu taraması) ———
    { giris: "Fırın eşit pişirmiyor (altı çiğ, üstü yanık)", tip: "belirti",
      anlam: "Tepsi konumu, dönmeyen fan ya da alt rezistans olabilir; kızarma testiyle ayrımı kendin yaparsın.",
      yazi: "firin-esit-pisirmiyor" },
    { giris: "Fırın kapağı açılmıyor / kilitli kaldı", tip: "belirti",
      anlam: "Çoğu zaman piroliz sonrası soğuma süresi ya da çocuk kilididir; kapıyı zorlamadan kontrol sırası.",
      yazi: "firin-kapagi-acilmiyor" },
    { giris: "Ocak alevi sarı ya da turuncu yanıyor", tip: "belirti",
      anlam: "Eksik yanma işaretidir, karbonmonoksit riski taşır; hangi durumda ocak kapatılır, ne güvenle temizlenir.",
      yazi: "ocak-alevi-sari-yaniyor" },
    { giris: "Elini çekince ocak sönüyor", tip: "belirti",
      anlam: "Çoğu zaman arıza değil, gaz emniyeti devrededir; termokupl mantığı ve 10-15 saniye basılı tutma tekniği.",
      yazi: "ocak-gaz-emniyeti-sonduruyor" },
    { giris: "Davlumbaz yağ filtresi temizliği", tip: "ayar",
      anlam: "Alüminyum filtre elde ya da makinede yıkanır; karbon filtre yıkanmaz, değiştirilir.",
      yazi: "davlumbaz-yag-filtresi-nasil-temizlenir" },
    { giris: "Fırın ne kadar elektrik harcar", tip: "ayar",
      anlam: "Saatte kaç kWh; sıcaklık-süre etkisi, ön ısıtma, turbo/fan modu ve kapak açma alışkanlığı.",
      yazi: "firin-ne-kadar-elektrik-harcar" },

  // ——— Kayıt genişletmesi (21 Ağu 2026, YK #80 · hedef 200+) ———
    { giris: "Davlumbaz zayıf çekiyor", tip: "belirti",
      anlam: "En sık sebep doymuş metal yağ filtresidir; ayda bir yıkanır ve çoğu model bulaşık makinesine girer.",
      yazi: "davlumbaz-cekmiyor" },
    { giris: "Çekiyor ama mutfakta koku kalıyor", tip: "belirti",
      anlam: "Bu ayrı bir belirtidir ve karbon filtreyi işaret eder; karbon filtre yıkanmaz, 3-6 ayda bir değiştirilir.",
      yazi: "davlumbaz-cekmiyor" },
    { giris: "Cam seramik ocak ısınmıyor", tip: "belirti",
      anlam: "Hiçbir göz çalışmıyorsa önce panel kilidine ve ocağın kendi sigortasına bakılır.",
      yazi: "cam-seramik-ocak-isinmiyor" },
    { giris: "İndüksiyonda tencere ısınmıyor", tip: "belirti",
      anlam: "İndüksiyon yalnız manyetik tabanlı tencereyi ısıtır; mıknatıs tabana sağlam yapışıyorsa tencere uyumludur.",
      yazi: "cam-seramik-ocak-isinmiyor" },
    { giris: "Ocağın tek gözü çalışmıyor", tip: "belirti",
      anlam: "Diğer gözler normalse besleme sağlamdır; o gözün ısıtıcısı ya da onu süren devre servis işidir.",
      yazi: "cam-seramik-ocak-isinmiyor" },
    { giris: "Panelde anahtar simgesi yanıyor", tip: "belirti",
      anlam: "Tuş ya da çocuk kilidi devrededir; ocak bütün komutları yok sayar, kilit simgesinin yanındaki tuşla açılır.",
      yazi: "cam-seramik-ocak-isinmiyor" },
    { giris: "Ocak kendi kendine kapanıyor", tip: "belirti",
      anlam: "Cam altındaki sıcaklık sınırı aşılınca göz kendini kapatır; sık tekrarlıyorsa sınırlayıcı ya da fan tarafı bakılır.",
      yazi: "cam-seramik-ocak-isinmiyor" },
    { giris: "Fırın ısınıyor ama yemek pişmiyor", tip: "belirti",
      anlam: "Geç ısınma da aynı listeye girer: rezistans, termostat, fan ve ısı kaçıran yıpranmış kapı contası.",
      yazi: "firin-isinmiyor" },
    { giris: "Fırın tek taraf ısıtıyor", tip: "belirti",
      anlam: "Alt ya da üst rezistanslardan biri yanmıştır; o ısıtıcının değişmesi gerekir.",
      yazi: "firin-isinmiyor" },
    { giris: "Turbo çalışmıyor, fan dönmüyor", tip: "belirti",
      anlam: "Sıcak havayı dağıtan fan dönmezse fırın düzgün ısınmaz; fan motoru servis tarafındadır.",
      yazi: "firin-isinmiyor" },
    { giris: "Kekin altı çiğ kalıyor", tip: "belirti",
      anlam: "Tepsi konumu, kalabalık fırın ya da alt rezistans olabilir; kızarma testiyle ayrımı kendin yaparsın.",
      yazi: "firin-esit-pisirmiyor" },
    { giris: "Çak çak ediyor ama yanmıyor", tip: "belirti",
      anlam: "Kıvılcım çıkıp alev tutmuyorsa başlık ıslak, kirli ya da yanlış oturmuştur; gaz vanasını da kontrol et.",
      yazi: "ocak-atesleme-yapmiyor" },
  // ——— 21 Ağu tur-3: tıklama odaklı kod + karar dalgası (12 yazı) ———
  // ⛔ `firin-tamiri-kac-para` ve `televizyon-tamiri-kac-para` BİLEREK BAĞLANMADI:
  //    başlıklarındaki "para" kelimesi kategori sayfasına sızıyor ve YK #35 şart 1'i
  //    ihlal ediyor (build 21 Ağu'da 3 sayfada yakaladı). Mevcut "…kaç para" yazıları da
  //    aynı sebeple bu ağaçta yok — istisna açılmadı. O yazılar /blog/ tarafında yaşıyor.
    { giris: "Fırın içi temizliği (piroliz · katalitik · buharlı)", tip: "ayar",
      anlam: "Hangi fırında hangi yöntem; katalitik yüzeye deterjan sürülmez, sprey nereye gitmemeli.",
      yazi: "firin-nasil-temizlenir" },
  ],

  "Televizyon / Monitör": [
    { giris: "Açılmıyor / standby ışığı yanıp sönüyor", tip: "belirti",
      anlam: "Güç kaynağı, kondansatör ve anakart ayrımı + kendin yapabileceğin kontroller.",
      yazi: "tv-acilmiyor" },
    { giris: "Ses var, görüntü yok", tip: "belirti",
      anlam: "Kaynak/kablo, arka ışık (backlight), panel ve güç kartı kaynaklı nedenler.",
      yazi: "televizyon-goruntu-gelmiyor" },
    { giris: "Ekranda çizgi, leke ya da kırık panel", tip: "belirti",
      anlam: "Dikey ve yatay çizgi farklı yerleri işaret eder; kablo ve kaynak elemeleri evde yapılır, panel işi serviste.",
      yazi: "tv-ekraninda-cizgi-var" },

  // ——— Boşluk dalgası (20 Ağu 2026, YK — 85-konu taraması) ———
    { giris: "Ekran kendiliğinden kararıyor", tip: "belirti",
      anlam: "Çoğu zaman güç tasarrufu ayarı ya da ortam ışığı sensörüdür; kontrol sırası belli.",
      yazi: "tv-ekrani-karariyor" },
    { giris: "HDMI girişinde sinyal yok", tip: "belirti",
      anlam: "Sorun çoğu zaman TV'de değil, kabloda ya da kaynak cihazdadır; doğru eleme sırasıyla evde bulunur.",
      yazi: "tv-hdmi-sinyal-yok" },
    { giris: "Monitör sinyal yok diyor, bilgisayar açık", tip: "belirti",
      anlam: "Kablo, yanlış giriş ya da ekran kartı çıkışı olabilir; eleme sırasıyla sorunu evde bul.",
      yazi: "monitor-sinyal-yok" },

  // ——— Kayıt genişletmesi (21 Ağu 2026, YK #80 · hedef 200+) ———
    { giris: "Açılışta logo geliyor, sonra ekran kararıyor", tip: "belirti",
      anlam: "Karanlık odada telefon feneriyle yapılan test, panelin mi arka aydınlatmanın mı sustuğunu ayırır.",
      yazi: "televizyonda-ses-var-goruntu-yok" },
    { giris: "Kırmızı ışık yanıyor ama açılmıyor", tip: "belirti",
      anlam: "Cihaza güç geliyor demektir; fişten çekip birkaç dakika beklemek geçirmezse anakart ya da güç kartı çıkışı şüphelidir.",
      yazi: "tv-acilmiyor" },
    { giris: "Fişte takılı ama hiç ışık yanmıyor", tip: "belirti",
      anlam: "Hiç gösterge yanmıyorsa önce priz, güç kablosu ve farklı priz denenir; sonrasında güç kaynağı kartı öne çıkar.",
      yazi: "tv-acilmiyor" },
    { giris: "Ekran karıncalanıyor", tip: "belirti",
      anlam: "Önce kaynak ve kablo elenir; bozuk görüntü sürüyorsa panele görüntüyü süren kart tarafı şüphelidir.",
      yazi: "televizyon-goruntu-gelmiyor" },
    { giris: "Isınınca çizgi beliriyor, soğukken kayboluyor", tip: "belirti",
      anlam: "Sıcaklıkla gelip giden çizgi aynı panel bağlantı bölgesini işaret eder ve kalıcılaşma eğilimi taşır; fotoğrafla belgele.",
      yazi: "tv-ekraninda-cizgi-var" },
    { giris: "Odanın ışığı azalınca ekran kısılıyor", tip: "belirti",
      anlam: "Ortam ışığı algılama açıkken televizyon parlaklığı kendisi düşürür; menüden kapatılıp sensörün önü açılır.",
      yazi: "tv-ekrani-karariyor" },
    { giris: "Bağladığım cihaz açık ama sinyal yok yazıyor", tip: "belirti",
      anlam: "Kaynak cihaz bekleme modundaysa ya da kumandadan yanlış giriş seçiliyse bu uyarı çıkar; eleme sırası bu yazıda.",
      yazi: "tv-hdmi-sinyal-yok" },
  // ——— 21 Ağu boşluk dalgası tur-2 (25 yeni yazı) ———
    { giris: "Uygulama açılmıyor / siyah ekranda kalıyor", tip: "belirti",
      anlam: "İnternet, önbellek, saat ve yazılım sırasıyla eleniyor; fabrika ayarı en sonda.",
      yazi: "smart-tv-uygulama-acilmiyor" },
    { giris: "Görüntü var, ses yok", tip: "belirti",
      anlam: "Sessiz mod, ses çıkışı ayarı, harici hoparlör ve panel hoparlörü sırasıyla kontrol ediliyor.",
      yazi: "tv-ses-gelmiyor" },
  // ——— 21 Ağu tur-3: tıklama odaklı kod + karar dalgası (12 yazı) ———
  // ⛔ `firin-tamiri-kac-para` ve `televizyon-tamiri-kac-para` BİLEREK BAĞLANMADI:
  //    başlıklarındaki "para" kelimesi kategori sayfasına sızıyor ve YK #35 şart 1'i
  //    ihlal ediyor (build 21 Ağu'da 3 sayfada yakaladı). Mevcut "…kaç para" yazıları da
  //    aynı sebeple bu ağaçta yok — istisna açılmadı. O yazılar /blog/ tarafında yaşıyor.
  ],

  "Mikrodalga / Air Fryer": [
    { giris: "Çalışıyor ama ısıtmıyor", tip: "belirti",
      anlam: "Magnetron, yüksek voltaj kapasitörü, kapı arızası ve düşük voltaj nedenleri.",
      yazi: "mikrodalga-isitmiyor" },
    { giris: "Hiç çalışmıyor / düğme-ekran tepki vermiyor", tip: "belirti",
      anlam: "Cihazın içi yüksek voltaj taşır; kapağı açmak kendin-çöz kapsamına girmez." },

  // ——— Boşluk dalgası (20 Ağu 2026, YK — 85-konu taraması) ———
    { giris: "Mikrodalga kıvılcım çıkarıyor", tip: "belirti",
      anlam: "Önce cihazı durdur; metal kap, yaldızlı tabak ve mika plakadaki yağ birikmesi en sık sebepler.",
      yazi: "mikrodalga-kivilcim-cikariyor" },
    { giris: "Airfryer — fan çalışıyor, ısıtmıyor", tip: "belirti",
      anlam: "Suçlu çoğu zaman rezistans değil, tam oturmamış sepettir; güvenlik anahtarı ısıtıcıyı kilitler.",
      yazi: "airfryer-isitmiyor" },

  // ——— Kayıt genişletmesi (21 Ağu 2026, YK #80 · hedef 200+) ———
    { giris: "Çalışıyor ama yemek soğuk kalıyor", tip: "belirti",
      anlam: "Işık yanıp tabla dönerken ısıtmama tablosu iç devreyi işaret eder; önce kapı, güç kademesi ve priz elenir.",
      yazi: "mikrodalga-isitmiyor" },
    { giris: "Yemek yalnız yüzeyinden ısınıyor", tip: "belirti",
      anlam: "Şebeke voltajı düşükse mikrodalga zayıf üretilir; yemek yüzeyden ya da çok yavaş ısınır.",
      yazi: "mikrodalga-isitmiyor" },
    { giris: "İçeride çatırtı ve parlama var", tip: "belirti",
      anlam: "Önce cihazı durdur; metal kap, yaldızlı tabak ve mika plakadaki yağ birikmesi en sık sebeplerdir.",
      yazi: "mikrodalga-kivilcim-cikariyor" },
    { giris: "Airfryer'da yemek çiğ kalıyor", tip: "belirti",
      anlam: "Fanın dönmesi yanıltmasın; tam oturmamış sepet güvenlik anahtarı üzerinden ısıtıcıyı kilitler.",
      yazi: "airfryer-isitmiyor" },
  ],

  "Süpürge": [
    // 22 Ağu 2026 (Tolga onayı, konu #3 → b): yazı rehbere yükseltildi → `rehber: true`.
    // YK #35 ② katman denetimi bunu ŞART koşuyor: kendi rehberimiz bir giriş satırından
    // erişilebilir olmalı, yoksa build DURUR (22 Ağu'da fiilen durdurdu).
    // ⛔ YK #31 kapsamı: 6 adımın hepsi ücretsiz/bakım seviyesi — söküm ve parça değişimi yok.
    { giris: "Çekmiyor / emiş zayıf", tip: "belirti",
      anlam: "Dolu hazne, tıkalı filtre, tıkanan hortum, aşınmış fırça ve motor ayrımı.",
      yazi: "supurge-cekmiyor", rehber: true },
    { giris: "Şarj tutmuyor", tip: "belirti",
      anlam: "Batarya döngü ömrü ve tıkalı filtrenin süreye etkisi; gerçekçi beklenti ve değişim yolu.",
      yazi: "sarjli-supurge-sarj-tutmuyor" },

  // ——— Boşluk dalgası (20 Ağu 2026, YK — 85-konu taraması) ———
    { giris: "Robot süpürge şarj olmuyor", tip: "belirti",
      anlam: "Çoğu zaman temas pinlerindeki kir ya da istasyonun yeridir; batarya ne zaman servise kalır.",
      yazi: "robot-supurge-sarj-olmuyor" },
    { giris: "Robot süpürgenin fırçası dönmüyor", tip: "belirti",
      anlam: "Çoğu zaman dolanan saç ve iptir, motor arızası nadirdir; hangi temizliği güvenle kendin yaparsın.",
      yazi: "robot-supurge-firca-donmuyor" },
    { giris: "Robot süpürge haritayı karıştırıyor / kayboluyor", tip: "belirti",
      anlam: "Sensör kiri, ayna-cam etkisi ya da taşınan dock olabilir; sıfırlamadan önce denenecekler.",
      yazi: "robot-supurge-haritalama-sorunu" },

  // ——— Kayıt genişletmesi (21 Ağu 2026, YK #80 · hedef 200+) ———
    { giris: "Emiş gücü azaldı", tip: "belirti",
      anlam: "Dolu hazne ve tıkalı filtre en yaygın gizli sebeptir; hortum, başlık fırçası ve hava kaçağı da sırayla elenir.",
      yazi: "supurge-cekmiyor" },
    { giris: "Yerden tozu almıyor, üstünden geçiyor", tip: "belirti",
      anlam: "Başlık fırçasına dolanan saç ve iplik yerden çekişi düşürür; fırça serbest dönene kadar temizlenir.",
      yazi: "supurge-cekmiyor" },
    { giris: "Süpürgeden yanık kokusu geliyor", tip: "belirti",
      anlam: "Yanık kokusu, aşırı ısınma ve anormal ses temizlikle çözülen belirtiler değildir; motor tarafını işaret eder.",
      yazi: "supurge-cekmiyor" },
    { giris: "Şarjlı süpürge çabuk bitiyor", tip: "belirti",
      anlam: "Suçlu her zaman batarya değil: tıkalı filtre motoru zorlayınca çalışma süresi de düşer.",
      yazi: "sarjli-supurge-sarj-tutmuyor" },
    { giris: "Robot dock'ta duruyor ama sabah boş", tip: "belirti",
      anlam: "En yaygın sebep temas pinlerindeki kir ve istasyonun oturmayan konumudur; batarya yaşlanmasının belirtileri ayrı.",
      yazi: "robot-supurge-sarj-olmuyor" },
    { giris: "Robot fırça uyarısı veriyor", tip: "belirti",
      anlam: "Ana fırçaya ve yan fırçaya dolanan saç-ip vakaların çoğunu açıklar; fırça yuvası ve emiş ağzı da kontrol edilir.",
      yazi: "robot-supurge-firca-donmuyor" },
  // ——— 21 Ağu boşluk dalgası tur-2 (25 yeni yazı) ———
    { giris: "Hortum tıkandı / çekiş düştü", tip: "belirti",
      anlam: "Işığa tutma testiyle tıkanıklığın yerini bulup hortumu zarar vermeden açıyorsun.",
      yazi: "supurge-hortumu-tikandi" },
  ],

  // ——— SU SEBİLİ / ARITMA (20 Ağu 2026) ———
  // Yazılar 19 Ağu'da yayına alınmıştı (PR #52) ama /tamir/ blog yazısından DEĞİL bu
  // dosyadan besleniyor; kayıt açılmadığı için hub'da "İçerik yok" görünüyordu.
  // `anlam` satırları yazıların KENDİ ilk bölüm başlıklarından türetildi, uydurulmadı.
  "Su Sebili / Arıtma": [
    { giris: "Soğuk su vermiyor / üstü buz tutuyor", tip: "belirti",
      anlam: "Çoğu durumda ayar kademesi düşüktür ya da arka havalandırma kapalıdır; ikisini de kendin kontrol edebilirsin.",
      yazi: "su-sebili-sogutmuyor" },
    { giris: "Altında su birikiyor", tip: "belirti",
      anlam: "En yaygın sebep dolan damlama tepsisi ve tam kapanmayan musluktur; damacananın oturuşunu da kontrol et.",
      yazi: "su-sebili-altinda-su-birikiyor" },
    { giris: "Arıtmadan su gelmiyor", tip: "belirti",
      anlam: "Önce giriş vanasına ve şebeke basıncına bak; tortu filtresi tıkalıysa akış durur.",
      yazi: "su-aritma-su-gelmiyor" },

  // ——— Kayıt genişletmesi (21 Ağu 2026, YK #80 · hedef 200+) ———
    { giris: "Su ılık geliyor", tip: "belirti",
      anlam: "Yeni takılan damacananın soğuması birkaç saat sürer; hüküm vermeden önce cihaza bir gece tanınır.",
      yazi: "su-sebili-sogutmuyor" },
    { giris: "Sıcak su geliyor, soğuk gelmiyor", tip: "belirti",
      anlam: "Sebilde sıcak ve soğuk taraflar bağımsız çalışır; birinin çalışması arızanın yalnız diğer tarafta olduğunu gösterir.",
      yazi: "su-sebili-sogutmuyor" },
    { giris: "Damacanayı değiştirdim, altından su akıyor", tip: "belirti",
      anlam: "Değişimde birkaç damla normaldir; dakikalar sonra da akıyorsa damacana tıkaca tam oturmamış ya da ağzı çatlaktır.",
      yazi: "su-sebili-altinda-su-birikiyor" },
    { giris: "Musluktan damla damla akıyor", tip: "belirti",
      anlam: "Kâğıt havlu testiyle hangi musluğun sızdırdığı bulunur; kolun altına oturmuş kireç ya da kırıntı kapanmayı engelliyor olabilir.",
      yazi: "su-sebili-altinda-su-birikiyor" },
    { giris: "Su çok yavaş akıyor", tip: "belirti",
      anlam: "Günler içinde yavaşlayan akış tıkanan tortu filtresinin tipik belirtisidir; ani kesilmede önce vana ve şebeke basıncı bakılır.",
      yazi: "su-aritma-su-gelmiyor" },
    { giris: "Cihaz sürekli çalışıyor ama su vermiyor", tip: "belirti",
      anlam: "Tankı doldurmaya çalışıp dolduramıyor demektir; sürekli çalışma pompaya zarar verdiği için cihaz kapatılıp servise danışılır.",
      yazi: "su-aritma-su-gelmiyor" },
  ],
  // ——— BİLGİSAYAR / YAZICI (20 Ağu 2026) ———
  "Bilgisayar / Yazıcı": [
    { giris: "Yazıcı çevrimdışı görünüyor", tip: "belirti",
      anlam: "Genellikle yazıcı uykudadır ya da bilgisayar yanlış yazıcıya gönderiyordur; kuyruğu sıfırlamak çoğu vakayı çözer.",
      yazi: "yazici-cevrimdisi-gorunuyor" },
    { giris: "Kâğıt çekmiyor", tip: "belirti",
      anlam: "Kâğıt nemli ya da yapraklar birbirine yapışmış olabilir; tepsi kılavuzlarını ve deste yüksekliğini de kontrol et.",
      yazi: "yazici-kagit-cekmiyor" },

  // ——— Boşluk dalgası (20 Ağu 2026, YK — 85-konu taraması) ———
    { giris: "Bilgisayar açılıyor ama ekran gelmiyor", tip: "belirti",
      anlam: "Önce monitör ve kablo elenir, sonra bip ve ışık sinyalleri okunur; hangi kontrol sana ait, hangisi servise.",
      yazi: "bilgisayar-acilmiyor-ekran-gelmiyor" },
    { giris: "Laptop ısınıyor, fan sesi kesilmiyor", tip: "belirti",
      anlam: "Çoğu zaman tıkalı hava kanalı ya da arka plan programlarıdır; hangi iş servise kalır.",
      yazi: "laptop-isiniyor-fan-sesi" },
    { giris: "Laptop şarj olmuyor", tip: "belirti",
      anlam: "Önce adaptör, kablo ve priz elenir; yüzde 80'de duran şarj çoğu zaman batarya koruma modudur.",
      yazi: "laptop-sarj-olmuyor" },
    { giris: "Yazıcı kartuşu tanımıyor", tip: "belirti",
      anlam: "Çoğu zaman temas noktası kirli ya da çip sorunludur; çıkar-tak, kuru bezle temizlik ve sürücü sıfırlama.",
      yazi: "yazici-kartus-tanimiyor" },
    { giris: "Yazıcı silik basıyor", tip: "belirti",
      anlam: "İlk şüpheli tıkalı püskürtme başlığıdır ve temizliği yazılımdan güvenle yapılır; nozzle check okuma.",
      yazi: "yazici-silik-basiyor" },
    { giris: "Yazıcı Wi-Fi'a bağlanmıyor", tip: "belirti",
      anlam: "Sıra önemli: önce modem, sonra yazıcı; çoğu yazıcı yalnız 2.4GHz destekler, WPS ve port kontrolüyle eleme.",
      yazi: "yazici-wifi-baglanmiyor" },

  // ——— Kayıt genişletmesi (21 Ağu 2026, YK #80 · hedef 200+) ———
    { giris: "Yazdır dedim ama çıkmıyor", tip: "belirti",
      anlam: "Belge kuyrukta bekliyorsa yazıcı çevrimdışıdır; kuyruğu boşaltıp cihazı kapatıp açmak çoğu vakayı çözer.",
      yazi: "yazici-cevrimdisi-gorunuyor" },
    { giris: "Tepside kâğıt var ama kâğıt yok diyor", tip: "belirti",
      anlam: "Nemli ya da birbirine yapışmış yapraklar, ayarsız tepsi kılavuzu ve yolda kalan bir yaprak aynı uyarıyı verir.",
      yazi: "yazici-kagit-cekmiyor" },
    { giris: "Açılışta bip sesleri geliyor", tip: "belirti",
      anlam: "Bip dizilimi ve kasa ışıkları BIOS'un arıza bildirimidir; hangi kontrol sana ait, hangisi servise.",
      yazi: "bilgisayar-acilmiyor-ekran-gelmiyor" },
    { giris: "Fan uçak gibi ses yapıyor", tip: "belirti",
      anlam: "Düzgün vınlama fanın değil, onu o devirde çalıştıran ısının işaretidir; zemin, hava kanalı ve arka plan programları elenir.",
      yazi: "laptop-isiniyor-fan-sesi" },
    { giris: "Fandan takırtı ve sürtme sesi geliyor", tip: "belirti",
      anlam: "Takırtı vınlamadan farklıdır: kanadın sürtmesine ya da yatağın yıpranmasına işaret eden mekanik bir bulgudur.",
      yazi: "laptop-isiniyor-fan-sesi" },
    { giris: "Takılı, şarj olmuyor yazıyor", tip: "belirti",
      anlam: "Çoğu vakada arıza değildir; önce priz, kablo ve adaptör elenir, sonra soket gevşekliği belirtilerine bakılır.",
      yazi: "laptop-sarj-olmuyor" },
    { giris: "Yeni kartuş taktım, tanımadı", tip: "belirti",
      anlam: "İlk şüpheli kirli temas noktası ve çiptir; çıkar-tak, kuru bezle temizlik ve sürücü sıfırlama sırayla denenir.",
      yazi: "yazici-kartus-tanimiyor" },
    { giris: "Mürekkep dolu görünüyor ama çıktı soluk", tip: "belirti",
      anlam: "Doluluk göstergesi püskürtme başlığının açık olduğunu göstermez; önce püskürtme denetimi deseni basılır.",
      yazi: "yazici-silik-basiyor" },
    { giris: "Yazıcı Wi-Fi ağını listede görmüyor", tip: "belirti",
      anlam: "En çok atlanan sebep frekans ayrımıdır: çoğu yazıcı yalnız 2.4GHz ağa bağlanır; sıra da önemli, önce modem.",
      yazi: "yazici-wifi-baglanmiyor" },
  // ——— 21 Ağu boşluk dalgası tur-2 (25 yeni yazı) ———
    { giris: "Bilgisayar yavaşladı", tip: "belirti",
      anlam: "Parça değiştirmeden önce yapılacak kontroller: başlangıç programları, disk doluluğu, ısınma.",
      yazi: "bilgisayar-yavas-calisiyor" },
    { giris: "Laptop klavyesi çalışmıyor", tip: "belirti",
      anlam: "Birkaç tuş mu tamamı mı sorusu arıza yerini söylüyor; evde ayrım yapılabiliyor.",
      yazi: "laptop-klavyesi-calismiyor" },
    { giris: "Yazıcıda kâğıt sıkıştı", tip: "belirti",
      anlam: "Doğru çekme yönü ve geride yırtık parça kaldı mı kontrolü; yanlış çekiş merdaneyi bozuyor.",
      yazi: "yazici-kagit-sikisti" },
  ],
};

/**
 * Bir cihazın ① katman kayıtlarını döndürür. Sıra sabittir: önce KOD, sonra BELİRTİ, sonra AYAR
 * (kullanıcı elindeki kodla gelir; kodu yoksa belirtiye, o da yoksa ayara bakar).
 * Kaydı olmayan cihazda boş dizi döner → sayfa basılmaz, hub'da dürüst "yok" kartı kalır.
 */
export const HATA_KODU_SIRA = ["kod", "belirti", "ayar"];

export function hataKoduKayitlari(cihaz) {
  // Alias-duyarlı (bkz. rehberBul): birleşen cihaz adı eski tablo anahtarına düşer.
  const liste = tabloBul(HATA_KODU_KATMANI, cihaz) || [];
  return HATA_KODU_SIRA.flatMap((t) => liste.filter((k) => k.tip === t));
}

/** Sayfada grup başlığı olarak basılan etiketler (tip → görünen ad). */
export const TIP_BASLIK = {
  kod: "Hata kodundan başla",
  belirti: "Belirtiden başla",
  ayar: "Ayar ve kullanım",
};

/** Kart üstündeki küçük etiket. Kendi rehberimiz varsa o öne çıkar (② kendin-çöz katmanı). */
export const TIP_ETIKET = { kod: "Hata kodu", belirti: "Belirti", ayar: "Ayar" };
