-- YK #166/#167 · 10 Eki 2026 · /pazar İLK KATALOG — 37 yedek parça, Benservis satıcı (dropship).
-- Tolga (10 Eki): "fiyatlar ve görselleri belirlediğin sitelerden gerçek al" · "diğer siteden
-- dropshipment yaparız, tahmini 3 iş günü de kargo süresine" · "her zaman kdv dahil fiyatlar olsun
-- ve fiyatları yukarı yuvarla ... 9lu fiyatlara" · "filigran olmamalı".
--
-- Kaynak: online-yedekparca.com ürün sayfalarının JSON-LD verisi (10 Eki okundu; site fiyatı
-- KDV HARİÇ verir → ×1,20). Satış fiyatı = tedarikçi KDV dahil × 1,20 (#167 +%20), sonu 9'a
-- yukarı yuvarlanmış, KDV DAHİL. Ham veri: benservis-icerik/pazar/2026-10-10-KATALOG-GERCEK-FIYAT.json
-- Görsel: tedarikçi görseli yalnız filigransızsa (20/37); filigranlı 17 üründe gorsel_url NULL →
-- vitrin cihaz ikonu basar. Temiz görsel bayi görüşmesinde istenir.
--
-- Stok: dropship, gerçek stok tedarikçide; vitrinde görünmesi için 10 yazılır (tedarikçi stoğu InStock).
-- Çalıştırma: Supabase SQL Editor (MCP/FE yazma yolu kapalı). Tekrar çalıştırılabilir:
-- aynı başlıklı Benservis ürünü varsa atlanır.
with bs as (select id from public.saticilar where tur = 'benservis' limit 1),
v(baslik, aciklama, fiyat, gorsel_url, parca_turu, cihaz_turu, kaynak) as (values
  ('Altus Ocak Döküm Izgara - Büyük', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 909, 'https://www.online-yedekparca.com/altus-cam-ocak-dokum-izgara-buyuk-bek-kapaklari-altus-13187-67-O.jpg', 'tabla-tepsi-izgara', 'firin-ocak-aspirator', 'https://www.online-yedekparca.com/altus-cam-ocak-dokum-izgara-buyuk'),
  ('Aspiratör Karbon Filtre - 16cm', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 159, null, 'filtre', 'firin-ocak-aspirator', 'https://www.online-yedekparca.com/aspirator-karbon-filtre-16cm'),
  ('Arçelik Ankastre Fırın Izgara Teli - 36cm x 46cm', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 409, 'https://www.online-yedekparca.com/arcelik-ankastre-firin-izgara-teli-36cm-x-46cm-aksesuar-arcelik-11272-55-O.jpg', 'tabla-tepsi-izgara', 'firin-ocak-aspirator', 'https://www.online-yedekparca.com/arcelik-ankastre-firin-izgara-teli-36cm-x-46cm'),
  ('Arçelik Fırın Emaye Tepsi - Orjinal', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 969, null, 'tabla-tepsi-izgara', 'firin-ocak-aspirator', 'https://www.online-yedekparca.com/arcelik-firin-emaye-tepsi'),
  ('Arçelik Set Üstü Ocak Gözü Izgara', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 609, null, 'tabla-tepsi-izgara', 'firin-ocak-aspirator', 'https://www.online-yedekparca.com/arcelik-set-ustu-ocak-gozu-izgara'),
  ('Fırın Ampülü - 300°', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 129, 'https://www.online-yedekparca.com/firin-ampulu-300-c-ampul-cesitleri-universal-1027-77-O.jpg', 'ampul-led-lamba', 'firin-ocak-aspirator', 'https://www.online-yedekparca.com/firin-ampulu-300-c'),
  ('Arçelik Ankastre Fırın Düğmesi', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 219, null, 'kumanda-dugme-tus', 'firin-ocak-aspirator', 'https://www.online-yedekparca.com/arcelik-ankastre-firin-dugme'),
  ('Arçelik Fırın Kapak Contası', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 729, null, 'lastik-conta', 'firin-ocak-aspirator', 'https://www.online-yedekparca.com/arcelik-firin-kapak-contasi'),
  ('Vestel Fırın Rezistansı - 32001562', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 419, 'https://www.online-yedekparca.com/vestel-firin-rezistansi-32001562-rezistans-cesitleri-vestel-75-58-O.jpg', 'rezistans-isitici', 'firin-ocak-aspirator', 'https://www.online-yedekparca.com/vestel-firin-rezistansi-32001562'),
  ('Arçelik Ocak Buji Ateşleme Grubu', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 429, null, 'brulor-atesleme', 'firin-ocak-aspirator', 'https://www.online-yedekparca.com/arcelik-ocak-buji-atesleme-grubu-268100034'),
  ('Demirdöküm Kombi NTC Isı Sensörü (Oring Contalı)', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 149, null, 'termostat-sensor', 'kombi-termosifon', 'https://www.online-yedekparca.com/demirdokum-kombi-ntc-isi-sensoru-oring-contali'),
  ('Vaillant Kombi Emniyet Ventili', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 239, 'https://www.online-yedekparca.com/vaillant-kombi-emniyet-ventili-emniyet-ventili-vaillant-10039-11-O.jpg', 'emniyet-ventili-presostat', 'kombi-termosifon', 'https://www.online-yedekparca.com/vaillant-kombi-emniyet-ventili'),
  ('Auer Micra Kombi Su Doldurma Musluğu', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 169, null, 'valf-vana-musluk', 'kombi-termosifon', 'https://www.online-yedekparca.com/auer-micra-kombi-su-doldurma-muslugu'),
  ('Baymak Kombi Plaka Eşanjör Contası', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 99, null, 'lastik-conta', 'kombi-termosifon', 'https://www.online-yedekparca.com/baymak-kombi-plaka-esanjor-contasi'),
  ('Bosch Kombi Termodinamik Genleşme Tankı 1/2', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 1929, 'https://www.online-yedekparca.com/bosch-kombi-termodinamik-genlesme-tanki-1-2-genlesme-tanki-bosch-11019-18-O.jpg', 'genlesme-tanki', 'kombi-termosifon', 'https://www.online-yedekparca.com/bosch-kombi-termodinamik-genlesme-tanki-1-2'),
  ('Demirdöküm Termosifon Rezistansı', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 649, null, 'rezistans-isitici', 'kombi-termosifon', 'https://www.online-yedekparca.com/demirdokum-termosifon-rezistansi'),
  ('Termosifon Emniyet Ventili - Mandallı', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 309, 'https://www.online-yedekparca.com/termosifon-emniyet-ventili-mandalli-muhtelif-malzemeler-uni-t-10946-54-O.jpg', 'emniyet-ventili-presostat', 'kombi-termosifon', 'https://www.online-yedekparca.com/termosifon-emniyet-ventili-mandalli'),
  ('Termosifon Anot Çubuğu - İnce (Kireç Tutucu)', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 359, 'https://www.online-yedekparca.com/termosifon-anot-cubugu-ince-rezistans-uni-t-8227-61-O.jpg', 'yedek-parca-genel', 'kombi-termosifon', 'https://www.online-yedekparca.com/termosifon-anot-cubugu-ince'),
  ('Beko Buzdolabı Alt Kapı Contası', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 2109, 'https://www.online-yedekparca.com/beko-buzdolabi-alt-kapi-contasi-4324852400-kapi-contasi-arcelik-545-42-O.jpg', 'lastik-conta', 'buzdolabi', 'https://www.online-yedekparca.com/beko-buzdolabi-alt-kapi-contasi-4324852400'),
  ('Arçelik Buzdolabı Sebzelik Örtüsü', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 1509, null, 'raf-sepet-cekmece', 'buzdolabi', 'https://www.online-yedekparca.com/arcelik-buzdolabi-sebzelik-ortusu-4305825500'),
  ('Arçelik Buzdolabı Kapı Şişe Rafı', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 729, 'https://www.online-yedekparca.com/buzdolabi-kapi-rafi-raf-cekmece-arcelik-6095-27-O.jpg', 'raf-sepet-cekmece', 'buzdolabi', 'https://www.online-yedekparca.com/buzdolabi-kapi-rafi'),
  ('Vestel Buzdolabı Termostatı (Eski Tip)', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 529, null, 'termostat-sensor', 'buzdolabi', 'https://www.online-yedekparca.com/vestel-buzdolabi-termostati-eski-tip'),
  ('Bosch Buzdolabı Fan Motoru - Orjinal', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 579, 'https://www.online-yedekparca.com/bosch-buzdolabi-fan-motoru-orjinal-fan-motoru-bosch-9192-34-O.jpg', 'fan-pervane', 'buzdolabi', 'https://www.online-yedekparca.com/bosch-buzdolabi-fan-motoru-orjinal'),
  ('Vestel Çamaşır Makinesi Kazan Hortumu - 42004356, 42127585', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 249, 'https://www.online-yedekparca.com/vestel-camasir-makinesi-kazan-hortumu-42004356-42127585-kazan-hortumlari-vestel-10749-25-O.jpg', 'hortum-boru-baca', 'camasir-makinesi', 'https://www.online-yedekparca.com/vestel-camasir-makinesi-kazan-hortumu-42004356-42127585'),
  ('Arçelik 9146 YK Çamaşır Makinesi Kazan Su Giriş Hortumu', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 609, null, 'hortum-boru-baca', 'camasir-makinesi', 'https://www.online-yedekparca.com/arcelik-9146-yk-camasir-makinesi-kazan-su-giris-hortumu'),
  ('Bosch Çamaşır Makinesi Pompa Kapağı', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 99, 'https://www.online-yedekparca.com/bosch-camasir-makinesi-pompa-filtre-kapagi-pompa-motoru-bosch-10172-37-O.jpg', 'filtre', 'camasir-makinesi', 'https://www.online-yedekparca.com/bosch-camasir-makinesi-pompa-filtre-kapagi'),
  ('Arçelik Çamaşır Makinesi Deterjan Çekmecesi', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 729, 'https://www.online-yedekparca.com/arcelik-camasir-makinesi-deterjan-cekmecesi-3183-deterjan-kutusu-arcelik-7088-31-O.jpg', 'deterjan-kutusu-cekmece', 'camasir-makinesi', 'https://www.online-yedekparca.com/arcelik-camasir-makinesi-deterjan-cekmecesi-3183'),
  ('Arçelik Çamaşır Makinesi Su Jetli Pompa Motoru', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 2109, 'https://www.online-yedekparca.com/arcelik-camasir-makinesi-su-jetli-pompa-motoru-pompa-motoru-arcelik-7488-89-O.jpg', 'motor', 'camasir-makinesi', 'https://www.online-yedekparca.com/arcelik-camasir-makinesi-su-jetli-pompa-motoru'),
  ('Profilo Çamaşır Makinesi Körüğü - Işıksız', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 429, 'https://www.online-yedekparca.com/profilo-camasir-makinesi-kazan-on-koruk-lastik-kazan-on-koruk-profilo-10235-19-O.jpg', 'lastik-conta', 'camasir-makinesi', 'https://www.online-yedekparca.com/profilo-camasir-makinesi-kazan-on-koruk-lastik'),
  ('Arçelik Bulaşık Makinesi Tahliye Hortumu - 44 cm', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 159, null, 'hortum-boru-baca', 'bulasik-makinesi', 'https://www.online-yedekparca.com/arcelik-bulasik-makinesi-tahliye-hortumu-44-cm'),
  ('Beko Bulaşık Makinesi Alt Sepet Tekerleği', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 39, 'https://www.online-yedekparca.com/beko-bulasik-makinesi-alt-sepet-tekerlegi-sepet-tekerlegi-beko-13071-82-O.jpg', 'raf-sepet-cekmece', 'bulasik-makinesi', 'https://www.online-yedekparca.com/beko-bulasik-makinesi-alt-sepet-tekerlegi'),
  ('Arçelik Bulaşık Makinesi Çatal Kaşık Sepeti Kaşıklık', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 369, null, 'raf-sepet-cekmece', 'bulasik-makinesi', 'https://www.online-yedekparca.com/arcelik-bulasik-makinesi-catal-kasik-sepeti-kasiklik-1751500300'),
  ('Arçelik Bulaşık Makinesi Alt Sızdırmazlık Contası - Orjinal', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 309, null, 'lastik-conta', 'bulasik-makinesi', 'https://www.online-yedekparca.com/arcelik-bulasik-alt-sizdirmazlik-contasi'),
  ('Sebil Musluk Soğuk Su (Orjinal)', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 99, 'https://www.online-yedekparca.com/sebil-musluk-soguk-su-orginal-sebil-musluk-universal-10787-22-O.jpg', 'valf-vana-musluk', 'su-sebili-aritma', 'https://www.online-yedekparca.com/sebil-musluk-soguk-su-orginal'),
  ('Klima İzolasyonlu Bakır Boru - 3/8-5/8', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 899, null, 'hortum-boru-baca', 'klima', 'https://www.online-yedekparca.com/klima-bakir-boru-38-58-izolasyonlu'),
  ('Klima Drenaj Hortumu', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 19, 'https://www.online-yedekparca.com/klima-5-8-drenaj-hortumu-1-mt-klima-drenaj-pompasi-universal-6464-28-O.jpg', 'hortum-boru-baca', 'klima', 'https://www.online-yedekparca.com/klima-5-8-drenaj-hortumu-1-mt'),
  ('Fakir Prestige Toz Torbası', 'Tedarikçiden doğrudan gönderilir; tahmini 3 iş gününde kargoda. Uyumlu model bilgisini sipariş öncesi teyit edin.', 129, 'https://www.online-yedekparca.com/fakir-prestige-toz-torbasi-toz-torbasi-fakir-7941-23-O.jpg', 'torba-toz-haznesi', 'supurge', 'https://www.online-yedekparca.com/fakir-prestige-toz-torbasi')
)
insert into public.servis_urunler
  (satici_id, tip, tur, kategori, baslik, aciklama, fiyat, gorsel_url, durum, stok, parca_turu, cihaz_turu, parca_durum)
select bs.id, 'yedek_parca', 'parca', 'yedek-parca', v.baslik, v.aciklama, v.fiyat, v.gorsel_url,
       'aktif', 10, v.parca_turu, v.cihaz_turu, 'yeni'
from v cross join bs
where not exists (
  select 1 from public.servis_urunler su where su.satici_id = bs.id and su.baslik = v.baslik
);

-- Doğrulama: select count(*) from public.servis_urunler su join public.saticilar s on s.id = su.satici_id
--            where s.tur = 'benservis' and su.durum = 'aktif' and su.kategori = 'yedek-parca';  -- 37 beklenir
